### ISSUE TITLE
Issue with Mail

### ISSUE THREAD

**Issue by amalfra** [peatio/peatio#397]
I have just setup peatio on my host and am facing issue with emails. It seems like the emails are not being send. I am using mandill for sending emails. Below is how i have in application.yml: 

SMTP_PORT: 587
  SMTP_DOMAIN: smtp.mandrillapp.com
  SMTP_ADDRESS: an email address
  SMTP_USERNAME: my username
  SMTP_PASSWORD: mt password
  SMTP_AUTHENTICATION: plain

Any help please?

**Comment by janx** [comment]
SMTP_ADDRESS should be smtp.mandrillapp.com

**Comment by amalfra** [comment]
Changed that but, still its the same....
