### ISSUE TITLE
Eventmachine prevent compatibility with Ruby 2.2.0

### ISSUE THREAD

**Issue by achiinto** [peatio/peatio#403]
Eventmachine is running 1.0.3 which is not compatiable for Ruby 2.2.0. EventMachine fixed this 15 days ago with https://github.com/eventmachine/eventmachine/issues/495 at release 1.0.4. 

Suggesting to change gemfile to eventmachine 1.0.4 or restrict project to Ruby lower than 2.2.0.

em.cpp:827:9: error: use of undeclared identifier 'rb_thread_select'; did you mean 'rb_thread_fd_select'?
        return EmSelect (maxsocket+1, &fdreads, &fdwrites, &fderrors, &tv);
               ^~~~~~~~
               rb_thread_fd_select
./em.h:25:20: note: expanded from macro 'EmSelect'
  #define EmSelect rb_thread_select

**Comment by lgn21st** [comment]
@achiinto fixed at https://github.com/peatio/peatio/commit/f0a0076094966c68ea9e6324565057fab98a3eec

But eventmachine is not the only issue for Ruby 2.2.0 compatibility, and support 2.2.0 is not our top priority at the moment, I suggest using Ruby 2.1.5 instead of it.

**Comment by achiinto** [comment]
@lgn21st my idea is that it would be best to restrict the ruby version and documented somewhere.
