### ISSUE TITLE
How can I cancel an open / or partially filled order ?

### ISSUE THREAD

**Issue by italiangirl** [peatio/peatio#405]
I am not sure, but I have not found it yet.. maybe I missed it...

On the site yunbi.com, it seems that they have implemented order cancelling

best greetings

**Comment by janx** [comment]
Just click the order you want to cancel.

**Comment by italiangirl** [comment]
oh thanks, I found it right now in the markets page. 

But it would also be convenient if we can cancel them at the ...../history/orders pages...

**Comment by janx** [comment]
History is read-only :-)
