### ISSUE TITLE
How and where in the code does the password get encrypted?

### ISSUE THREAD

**Issue by italiangirl** [peatio/peatio#408]
I am reading through the code, and I am not a good ruby programmer I have to admit...

I would like to know, where in the code does the password get hashed and what algorithm does it use?   I know that the hashed (scrambled) password gets then saved into the table named identities and column is named password_digest. In there then the password stays hashed or lets say encrypted. 
Do you have any ideas?

**Comment by lgn21st** [comment]
@italiangirl The work of hash the password with salt done by the gem `omniauth-identity`, here is a podcast video about it and explain very well, wish it could answer your question.

http://railscasts.com/episodes/304-omniauth-identity

**Comment by italiangirl** [comment]
I see, thanks, 

I have some other questions, I will post them on the issues main page
