### ISSUE TITLE
Currency "cny" is hard coded? 

### ISSUE THREAD

**Issue by foalford** [peatio/peatio#414]
Find that `cny` is hard coded in controller and templates. Just want to confirm that change cny to other currency would require a change of code in addition to `currencies.yml`

True ?

**Comment by janx** [comment]
I guess you're referring to deposit/withdraw classes? Those're generated by rails generator, check `rails g deposit` and `rails g withdraw`.

In principal, you needn't MODIFY any cny classes to make a new currency work (deposit/withdraw/trade), ADD new classes should be enough. Let me know if that's not the case.

**Comment by foalford** [comment]
I guess that I should try #318
