### ISSUE TITLE
403 from POST /deposits/satoshis/gen_address

### ISSUE THREAD

**Issue by foalford** [peatio/peatio#415]
I set the currencies.yml using a local regtest bitcoin. However I got 403 on generating new address. Looking at the code, it seems like in `app/controllers/concerns/deposits/ctrl_coinable.rb`
```
if !account.payment_address.transactions.empty?
```
evaluate to false. 

Is there some configuration that I missed?

**Comment by janx** [comment]
That line is used to prevent user generate new address until current address is used.

**Comment by foalford** [comment]
This question was wrong. Reason was that I didn't obtain the address in the first place. Where I experienced was that my firefox having issue displaying the warning message, which is 
`it can't generate new address if it hasn't been used.`. However, my chrome is fine. 

Anyway, this isn't an issue.  Thx.

**Comment by valuead** [comment]
how was this resolved?
