### ISSUE TITLE
Withdraw coin request get rejected in a minute automatically

### ISSUE THREAD

**Issue by foalford** [peatio/peatio#416]
Withdrawal of bitcoin request was made successfully however it changed the status to `rejected` very soon afterwards. 

Everything looks normal in logs. Wonder if that it's somewhere the rabbitmq got messed up. Mind of point ing a direction where I should look into? 

Thx

**Comment by italiangirl** [comment]
I also have problems with withdrawals. But different one. 

concerning your posting, I assume when it changes the status to rejected ,then it will eventually unlock the funds and increase the balance in mysql database? Did you look up in mysql database wheather it also changed the balance?

**Comment by foalford** [comment]
Saw yours. Cannot help though. 
I didn't check database directly. But there is a moment after withdrawal and before the rejection, the coin balance locked up. It is soon unlocked after rejection. 

Even though the real withdrawal can be processed in backend, the frontend should be aligned with it. I think it's working. But somehow somewhere is wrong. I will keep digging. But this part isn't easy.

**Comment by janx** [comment]
Read `lib/daemons/withdraw_audit.rb`.

**Comment by foalford** [comment]
Got it. `result[:ismine] == true`. Looks like there is no feature to move coin within the exchange. Actually it should be just as easy as a database change.

**Comment by italiangirl** [comment]
yes, this is something I also found out today. 

It would be a good feature to move coins between accounts internally as well.

**Comment by lgn21st** [comment]
Actually you cannot make a transaction between two address that belongs to same wallet, it not our problem, but the restrict of Bitcoin protocol, I'll close this issue.
