### ISSUE TITLE
YES-BTC出了什么样的问题呢？他们用的是PEATIO的程序不是

### ISSUE THREAD

**Issue by summm** [peatio/peatio#417]
之前的首页交易所列表里有看到它在列表里，现在删除掉了
是PEATIO程序出了问题吗？

**Comment by janx** [comment]
Check their facebook page: https://www.facebook.com/yesbtc

![selection_471](https://cloud.githubusercontent.com/assets/5958/6052783/383e91ca-ad12-11e4-897d-7b7b90473d78.png)
![selection_472](https://cloud.githubusercontent.com/assets/5958/6052784/399cbb00-ad12-11e4-8024-b23a9780f3bd.png)
