### ISSUE TITLE
Market Chart wont load

### ISSUE THREAD

**Issue by CryptNZ** [peatio/peatio#418]
Have installed a fresh install of Peatio on a fresh install of Ubuntu 14.04

Using ENV=Production etc, trying to view market charts produces the following error in chrome and internet explorer

"Uncaught TypeError: Cannot read property 'tid' of undefined"

Have searched other issues, and seen this was an issue in December but says it was fixed.

**Comment by janx** [comment]
Can you paste the full js error stack? It can be found in chrome console.

**Comment by CryptNZ** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10857964/6053264/13c51172-ad42-11e4-9ac8-6ad7f347d142.png)

Thats all that it says

**Comment by CryptNZ** [comment]
Sorry @janx full log here:

![untitled](https://cloud.githubusercontent.com/assets/10857964/6054098/ac3b5820-ad4d-11e4-8c75-ef0cd10454ee.png)

**Comment by janx** [comment]
@CryptNZ thanks!

Fixed by https://github.com/peatio/peatio/commit/afde9f7ba8349496d6ee09f1a4f89b63c6aff4cc
