### ISSUE TITLE
Market switch width - firefox

### ISSUE THREAD

**Issue by Jarinzbazin** [peatio/peatio#424]
On Firefox problem with width market switch, IE & Chrome is ok.

![market-switch](https://cloud.githubusercontent.com/assets/9196509/6165451/56c08964-b2a8-11e4-9133-4b4368bd89ac.png)

**Comment by janx** [comment]
Here we don't use flexible layout, you'd better adjust the width manually to accommodate high precision numbers.

The width is defined at:
https://github.com/peatio/peatio/blob/master/app/assets/stylesheets/vars/_market.css.scss#L31

Table column width is controlled by bootstrap classes:
https://github.com/peatio/peatio/blob/master/app/views/private/markets/_market_list.html.slim
https://github.com/peatio/peatio/blob/master/app/views/private/markets/_market_trades.html.slim
