### ISSUE TITLE
Step 9 of install produces error

### ISSUE THREAD

**Issue by jackthursby** [peatio/peatio#425]
x@ubuntu:/usr/local/share/peatio$ bundle install
Fetching source index from https://rubygems.org/
Using rake (10.4.2) 
Using aasm (3.4.0) 
Using i18n (0.7.0) 
Using minitest (4.7.5) 
Using multi_json (1.10.1) 
Using atomic (1.1.99) 
Using thread_safe (0.1.3) 
Using tzinfo (0.3.42) 
Using activesupport (4.0.12) 
Using builder (3.1.4) 
Using erubis (2.7.0) 
Using rack (1.5.2) 
Using rack-test (0.6.3) 
Using actionpack (4.0.12) 
Using mime-types (1.25.1) 
Using mail (2.6.3) 
Using actionmailer (4.0.12) 
Using active_hash (1.3.0) 
Using activemodel (4.0.12) 
Using activerecord-deprecated_finders (1.0.3) 
Using arel (4.0.2) 
Using activerecord (4.0.12) 
Using bundler (1.3.5) 
Using thor (0.19.1) 
Using railties (4.0.12) 
Using hike (1.2.3) 
Using tilt (1.4.1) 
Using sprockets (2.11.0) 
Using sprockets-rails (2.2.2) 
Using rails (4.0.12) 
Using acts-as-taggable-on (3.0.1) 
Using addressable (2.3.5) 
Using amq-protocol (1.9.2) 
Using eventmachine (1.0.4) 
Using amqp (1.3.0) 
Using angularjs-rails (1.3.0) 
Using awesome_print (1.2.0) 
Using descendants_tracker (0.0.3) 
Using ice_nine (0.11.0) 
Using axiom-types (0.1.0) 
Using bcrypt-ruby (3.1.2) 
Using coderay (1.1.0) 
Using better_errors (1.1.0) 
Using debug_inspector (0.0.2) 
Using binding_of_caller (0.7.2) 
Using sass (3.2.19) 
Using bootstrap-sass (3.2.0.2) 
Using bootstrap-wysihtml5-rails (0.3.1.23) 
Using bourbon (3.2.3) 
Using browser (0.8.0) 
Using bunny (1.2.1) 
Using columnize (0.3.6) 
Using debugger-linecache (1.2.0) 
Installing byebug (2.7.0) 
Gem::InstallError: byebug requires Ruby version >= 2.0.0.
An error occurred while installing byebug (2.7.0), and Bundler cannot continue.
Make sure that `gem install byebug -v '2.7.0'` succeeds before bundling.

**Comment by janx** [comment]
`Gem::InstallError: byebug requires Ruby version >= 2.0.0.`

**Comment by cubebarn** [comment]
current directory:
/tmp/bundler20170111-9127-t0kmxbatomic-1.1.99/gems/atomic-1.1.99/ext
/usr/bin/ruby2.3 -r ./siteconf20170111-9127-1slez47.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in
/tmp/bundler20170111-9127-t0kmxbatomic-1.1.99/gems/atomic-1.1.99 for inspection.
Results logged to
/tmp/bundler20170111-9127-t0kmxbatomic-1.1.99/extensions/x86_64-linux/2.3.0/atomic-1.1.99/gem_make.out

An error occurred while installing atomic (1.1.99), and Bundler cannot
continue.
Make sure that `gem install atomic -v '1.1.99'` succeeds before bundling.

**Comment by cesar-valdez** [comment]
I have ubuntu 16.4 I had the same error in my project

**my solution is to install ruby, rbenv, bundler finally delete and create Gemfile file:**


**first step: install ruby**

**update system**
 

    sudo apt-get update           
    sudo apt-get upgrade


**rbenv**

    sudo apt-get install git-core curl zlib1g-dev build-essential \   
                             libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 \
                             libxml2-dev libxslt1-dev libcurl4-openssl-dev \
                             python-software-properties libffi-dev
        
    
    
        git clone git://github.com/sstephenson/rbenv.git .rbenv
        echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
        echo 'eval "$(rbenv init -)"' >> ~/.bashrc
        exec $SHELL

**ruby-build**

    git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
    echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
    exec $SHELL


**Install Ruby through rbenv:**

    rbenv install 2.2.1
    rbenv global 2.2.1


**Install bundler**

    echo "gem: --no-ri --no-rdoc" > ~/.gemrc
    gem install bundler
    rbenv rehash


**second step: delete and create the Gemfile file**

Search for the Gemfile file in the project, it must be at the root of the project. for more information about Gemfile http://bundler.io/

    cd peatio

with the command ls we can see all the files and folders of the project

    ls

delete Gemfile file

    rm Gemfile

create Gemfile

    bundle init

now we can install bundle

    bundle install
