### ISSUE TITLE
mulcoin lets everyone edit their redis database. Why so unsecured ?

### ISSUE THREAD

**Issue by ooowos45653hs** [peatio/peatio#426]
mulcoin.com has the redis port open. And NO password auth. 

Everybody can hack now. 
If they also offer cookies session via redis instance, then bitcoins are gone....

**Comment by ooowos45653hs** [comment]
they also have open rabbitmq ports. But at least these are password secured.

**Comment by janx** [comment]
We'll contact them so they aware of this, and remove them from our README list.

Thanks.
