### ISSUE TITLE
Multisig

### ISSUE THREAD

**Issue by arruah** [peatio/peatio#427]
Guys, is it difficult to implement it in this project? There have been three break several exchanges this week.
This approach should improve security. Or am I mistaken?

**Comment by bencxr** [comment]
Hi Arruah,

I have been working on a multisig implementation using BitGo as a co-signer for the outgoing transactions. Please get in touch if interested.

**Comment by arruah** [comment]
Do you have plans to share it here?

**Comment by bencxr** [comment]
Yes I do. But contact me if you want to get an early look.

**Comment by arruah** [comment]
Is it your article? 
https://medium.com/@benedictchan/building-the-world-s-first-open-source-multi-sig-bitcoin-exchange-a6f1221eff46

**Comment by janx** [comment]
Nice work :beers:

**Comment by bencxr** [comment]
Yes that was me. Please do get in touch if you need help with multisig.

**Comment by arruah** [comment]
I will.

**Comment by hrishikeshio** [comment]
Please close this issue.
