### ISSUE TITLE
rake aborted, syntaxerror

### ISSUE THREAD

**Issue by zongyii** [peatio/peatio#428]
getting error while rake db:setup, any help ?

deploy@li942-39:~/peatio/current$ bundle exec rake db:setup
rake aborted!
Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 6 column 3
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/figaro-0.7.0/lib/figaro.rb:21:in `raw'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/figaro-0.7.0/lib/figaro.rb:17:in `env'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/figaro-0.7.0/lib/figaro/railtie.rb:7:in `block in <class:Railtie>'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:36:in `call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:44:in `each'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/railties-4.0.12/lib/rails/application.rb:67:in `inherited'
/home/deploy/peatio/current/config/application.rb:15:in `<module:Peatio>'
/home/deploy/peatio/current/config/application.rb:14:in `<top (required)>'
/home/deploy/peatio/current/Rakefile:5:in `require'
/home/deploy/peatio/current/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by janx** [comment]
`Psych::SyntaxError: (): did not find expected key while parsing a block mapping at line 6 column 3`

Syntax error in your 'config/application.yml'
