### ISSUE TITLE
is there a minimum memory requirement ?

### ISSUE THREAD

**Issue by zongyii** [peatio/peatio#429]
i am on 1GB ram, is it necessary to have at least 2GB ram ? 

there has been an error -  'cannot allocate memory' , 

deploy@localhost:~/peatio/current$ bundle exec rake daemons:start
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/daemonize.rb:11:in `fork': Cannot allocate memory - fork(2) (Errno::ENOMEM)
	from /home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/daemonize.rb:11:in `safefork'
	from /home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/daemonize.rb:93:in `daemonize'
	from /home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:146:in `start_load'
	from /home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
	from /home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
	from /home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
	from /home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
	from lib/daemons/stats_ctl:6:in `<main>'
pid-file for killed process 6538 found (/home/deploy/peatio/current/log/peatio:amqp:pusher:1.pid), deleting.
pid-file for killed process 6546 found (/home/deploy/peatio/current/log/payment_transaction.rb.pid), deleting.
pid-file for killed process 6558 found (/home/deploy/peatio/current/log/peatio:amqp:order_processor:1.pid), deleting.
pid-file for killed process 6566 found (/home/deploy/peatio/current/log/peatio:amqp:market_data.pid), deleting.
pid-file for killed process 6588 found (/home/deploy/peatio/current/log/peatio:amqp:notification.pid), deleting.
pid-file for killed process 6608 found (/home/deploy/peatio/current/log/global_state.rb.pid), deleting.

**Comment by janx** [comment]
Yes, 1GB is not enough.
