### ISSUE TITLE
Cannot restart properly

### ISSUE THREAD

**Issue by bencxr** [peatio/peatio#430]
When making configuration changes, what is the best way to restart peatio?
I am using passenger, and I stop nginx and do bundle exec rake daemons:stop
and then I do bundle exec rake daemons:start

however, whenever I do this, all the daemons start behaving erratically and I see this stacktrace:
E, [2015-02-17T04:52:46.535613 #4202] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `read_nonblock'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `_read_from_socket'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:41:in `gets'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:273:in `read'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:229:in `block in read'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:220:in `io'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:228:in `read'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `block in call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:201:in `block (2 levels) in process'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:309:in `ensure_connected'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis.rb:784:in `block in get'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis.rb:783:in `get'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-store-1.1.4/lib/redis/store/interface.rb:5:in `get'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:17:in `get'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:169:in `read_entry'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/cache.rb:314:in `block in read'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/cache.rb:519:in `instrument'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/cache.rb:313:in `read'
/home/deploy/peatio/current/app/models/global.rb:51:in `bids'
/home/deploy/peatio/current/app/models/global.rb:84:in `trigger_orderbook'
/home/deploy/peatio/current/lib/daemons/global_state.rb:20:in `block in <top (required)>'
/home/deploy/peatio/current/lib/daemons/global_state.rb:18:in `each'
/home/deploy/peatio/current/lib/daemons/global_state.rb:18:in `<top (required)>'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/global_state_ctl:6:in `<main>'

E, [2015-02-17T04:52:46.535716 #4202] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `read_nonblock'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `_read_from_socket'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:41:in `gets'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:273:in `read'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:229:in `block in read'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:220:in `io'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:228:in `read'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `block in call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:201:in `block (2 levels) in process'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:309:in `ensure_connected'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis.rb:784:in `block in get'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-3.0.7/lib/redis.rb:783:in `get'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-store-1.1.4/lib/redis/store/interface.rb:5:in `get'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:17:in `get'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:169:in `read_entry'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/cache.rb:314:in `block in read'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/cache.rb:519:in `instrument'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/cache.rb:313:in `read'
/home/deploy/peatio/current/app/models/global.rb:47:in `asks'
/home/deploy/peatio/current/app/models/global.rb:84:in `trigger_orderbook'
/home/deploy/peatio/current/lib/daemons/global_state.rb:20:in `block in <top (required)>'
/home/deploy/peatio/current/lib/daemons/global_state.rb:18:in `each'
/home/deploy/peatio/current/lib/daemons/global_state.rb:18:in `<top (required)>'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/deploy/peatio/current/vendor/bundle/ruby/2.1.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'

If I reboot the VM, Peatio starts fine again.

**Comment by lgn21st** [comment]
just run command `touch tmp/restart.txt`

https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#_redeploying_restarting_the_rack_application

**Comment by janx** [comment]
You can ignore such errors in daemon.log, check daemon.output instead.

**Comment by bencxr** [comment]
I also want to restart the daemons. does touch tmp/restart.txt do that as well?

**Comment by janx** [comment]
No, it only restarts passenger, use rake to restart daemons.
