### ISSUE TITLE
Instalation failed at last step

### ISSUE THREAD

**Issue by jackthursby** [peatio/peatio#431]
I'm attempting to install this on VMware before I do anything else. This is the 10th or so attempt so any help might stop me from going insane.

eggsnbacon@ubuntu:/usr/local/share/peatio$ bundle exec rails server
=> Booting WEBrick
=> Rails 4.0.12 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/home/eggsnbacon/.rbenv/versions/2.1.2/lib/ruby/2.1.0/fileutils.rb:250:in `mkdir': Permission denied @ dir_s_mkdir - /usr/local/share/peatio/tmp (Errno::EACCES)
	from /home/eggsnbacon/.rbenv/versions/2.1.2/lib/ruby/2.1.0/fileutils.rb:250:in `fu_mkdir'
	from /home/eggsnbacon/.rbenv/versions/2.1.2/lib/ruby/2.1.0/fileutils.rb:224:in `block (2 levels) in mkdir_p'
	from /home/eggsnbacon/.rbenv/versions/2.1.2/lib/ruby/2.1.0/fileutils.rb:222:in `reverse_each'
	from /home/eggsnbacon/.rbenv/versions/2.1.2/lib/ruby/2.1.0/fileutils.rb:222:in `block in mkdir_p'
	from /home/eggsnbacon/.rbenv/versions/2.1.2/lib/ruby/2.1.0/fileutils.rb:208:in `each'
	from /home/eggsnbacon/.rbenv/versions/2.1.2/lib/ruby/2.1.0/fileutils.rb:208:in `mkdir_p'
	from /home/eggsnbacon/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.0.12/lib/rails/commands/server.rb:71:in `block in start'
	from /home/eggsnbacon/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.0.12/lib/rails/commands/server.rb:70:in `each'
	from /home/eggsnbacon/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.0.12/lib/rails/commands/server.rb:70:in `start'
	from /home/eggsnbacon/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.0.12/lib/rails/commands.rb:76:in `block in <top (required)>'
	from /home/eggsnbacon/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.0.12/lib/rails/commands.rb:71:in `tap'
	from /home/eggsnbacon/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.0.12/lib/rails/commands.rb:71:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
eggsnbacon@ubuntu:/usr/local/share/peatio$

**Comment by janx** [comment]
The log tells:

/home/eggsnbacon/.rbenv/versions/2.1.2/lib/ruby/2.1.0/fileutils.rb:250:in mkdir': Permission denied @ dir_s_mkdir - /usr/local/share/peatio/tmp (Errno::EACCES)

**Comment by jackthursby** [comment]
That's not helpful.

**Comment by CryptNZ** [comment]
Trying running as sudo, or check you have the available permissions.

**Comment by janx** [comment]
Then do your homework. This is not a linux 101 forum.

**Comment by jackthursby** [comment]
Thanks that's really helpful.

**Comment by jackthursby** [comment]
The snobbishness of the Linux user. I follow the instructions given word for word and they don't work. When I ask for the answer I am told to study Linux. I have a suggestion to save people allot of time: place in bold capitals at the top of your installation development and production instructions "WARNING WE ARE WASTING YOUR TIME THESE INSTRUCTIONS DON'T WORK AND ITS YOUR FAULT IF YOU FOLLOW THEM"
