### ISSUE TITLE
Integrating Ripple

### ISSUE THREAD

**Issue by zackkoGH** [peatio/peatio#434]
How about integrating some decentralized technology like Ripple/Bitshares inside the exchange?
Ripple: https://ripple.com/knowledge-center/
BitShares: https://bitshares.org/how-it-works

**Comment by outbackdingo** [comment]
interesting.....

**Comment by zackkoGH** [comment]
I'm working on another project at the moment, but as soon as I've finish with this I will take a look at your code and try to work a solution for that.

Decentraized exchanges are the future.

Also... the learning curve of your technology will be quite slow as I'm a Java developer not a Ruby developer. I hope to have an answer in the next 2 weeks. 

My idea is a truly decentralized cryptocurrency is Ethereum at the moment, a cryptocurrency that permits a truly decentralized echange. The decentralized exchange currently built on top of the Ethereum technology stack is EtherEx:
http://www.etherex.org/

You will give me the opportunity to know more about an internal engine of an Exchange. 

Thanks for doing this project.

**Comment by janx** [comment]
Doable, may need to modify some code if the deposit design is different than BTC, e.g. BTS deposit is account+memo, not user specific address.

**Comment by zackkoGH** [comment]
Infact the subject of the issue is "Integrating Ripple".
Integrating means:  "To make into a whole by bringing all parts together; unify" (ref: http://www.thefreedictionary.com/integrating) so a new module for decentralised systems needs to be added to the codebase.

Again, as I stated in my comment I will do that in the next months as soon as I'll learn some Ruby.

Now I know your opinion on that. 

Thanks.

**Comment by dapeng313** [comment]
hi. @zackkoGH  Did you integrated Decentralized Cryptocurreny here?
It looks interesting..

**Comment by dapeng313** [comment]
who have implemented Ripple?
i wanna discuss sth with him.

**Comment by zackkoGH** [comment]
Hi guys,
My cryptocurrency business got shutted down cause problems with "banking relationship": I'm searching funds for starting up a new venture in this market.

**No**: I didn't had time to implement the patio-Ripple integration.

I will look into it as soon as I will come back in cryptocurrency development.

Thank You for your question.

Best regards.

**Comment by gouthamvel** [comment]
Did any development happen on this feature? I'm looking into building one.

**Comment by MaffeProg** [comment]
https://ripple.com/files/xrp_exchanges.pdf

I'm going to integrate most coins soon. But you can start already
