### ISSUE TITLE
Sprockets::FileNotFound: couldn't find file 'bootstrap-wysihtml5/b3'

### ISSUE THREAD

**Issue by foalford** [peatio/peatio#435]
`RAILS_ENV=production bundle exec rake assets:precompile` generate an error

> rake aborted!
> Sprockets::FileNotFound: couldn't find file 'bootstrap-wysihtml5/b3'
>   (in /home/app/webapp/app/assets/javascripts/admin.js:4)

While the relavent gems are

>    bootstrap-wysihtml5-rails (0.3.3.6)
>      railties (>= 3.0)

Wonder if there is a quick fix? Or any direction if not?

**Comment by janx** [comment]
Compare your Gemfile.lock with the one on github.

**Comment by tkembo** [comment]
Where you ever able to resolve this?

**Comment by raisty** [comment]
Same issue

**Comment by eric-tsoi** [comment]
rename files in scss and js to what?

**Comment by eric-tsoi** [comment]
How does this get fixed? Thanks

**Comment by muhammednagy** [comment]
@tkembo  did you fix it?

**Comment by foalford** [comment]
Yes. It was fixed. Follow janx's comment. 

BTW, we started our own business of whitelabel exchanges, which is based on the peatio code base.

**Comment by muhammednagy** [comment]
Same here
By the way who are you? :D

**Comment by foalford** [comment]
No. That's not a successful business. The code is good but not the business. In regarding to the issue itself, there is nothing new. Just follow Janx's comment.

**Comment by aejontargaryen** [comment]
If you say so.
Just compare the file from github with the file from github.
Got it
