### ISSUE TITLE
I18n

### ISSUE THREAD

**Issue by arruah** [peatio/peatio#436]
I'm trying to add to the project Russian localization. The logs out error. 
I, [2015-03-13T16:27:26.445194 #5766]  INFO -- : Started GET "/javascripts/locales/ru_RU.js" for 2.135.99.122 at 2015-03-13 16:27:26 +0600
F, [2015-03-13T16:27:26.449319 #5766] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/javascripts/locales/ru_RU.js"):
  lib/middleware/security.rb:11:in `call'
In my config/application.rb
    config.i18n.load_path += Dir[Rails.root.join('config', 'locales', 'custom', '*.{yml}')]
    config.i18n.available_locales = ['en', 'ru_RU', 'zh-CN']

**Comment by janx** [comment]
cc @lgn21st

**Comment by arruah** [comment]
![2015-03-14 16 43 38](https://cloud.githubusercontent.com/assets/67720/6651372/716d5b38-ca69-11e4-9736-508c08e893bb.png)

**Comment by arruah** [comment]
Solved. Thanks.

**Comment by shapiroisme** [comment]
How solved?

**Comment by vetal20600** [comment]
Same issue. With new language.
Any solution?
