### ISSUE TITLE
Peatio Sucks Balls

### ISSUE THREAD

**Issue by jackthursby** [peatio/peatio#437]
Installation instructions when followed to the word will not work. If you inform the developers of this they wont offer any help. Peatio is a half arsed attempt at software created by hacks don't waste your time with this. It doesn't work. I pay a developer £350 to install it. It still doesn't work. I paid £350 for web page with a picture of a lion on it. You will need to pay them thousands of dollars before this crap will work. Better to write an exchange yourself at least then you know it will be secure.

**Comment by valuead** [comment]
Works for all doesn’t work for you 

Reading what you wrote speak volume about you. Get lost.
