### ISSUE TITLE
[Question] Development version of Peatio inside of a docker container?

### ISSUE THREAD

**Issue by brossi** [peatio/peatio#438]
Has anyone attempted to build Peatio for development inside of a Docker container? We use our Peatio exchange for internal testing to simulate exchanges that the tool we're developing runs on.

One of the asks from the development team that I work with is to be able to set up isolated tests for different conditions. Peatio is able to do this in development mode using the test suite that it already comes with, but I'd like to make it as streamlined a process as possible and the isolation that a Docker container gives makes it attractive for the purpose.

Before I started down the path of writing a Docker file to encapsulate Peatio it occurred to me that I should ask to see if anyone has an existing one that I could work from. 

Thanks!

**Comment by janx** [comment]
I remember @hpyhacking created a docker container for himself.

@hpyhacking can you confirm?

**Comment by brossi** [comment]
@hpyhacking: do you have any comments on setting this up? If you preferred, we could discuss this offline if it was easier.

**Comment by hpyhacking** [comment]
@brossi We just only use docker for deploy and I will add deploy sample `Dockerfile` to repo ASAP.

**Comment by brossi** [comment]
Awesome, thank you @hpyhacking! Much appreciated.
