### ISSUE TITLE
Does this line contain a typo or is it coded as intended?

### ISSUE THREAD

**Issue by brossi** [peatio/peatio#439]
Branch: Master
Reference: app/assets/javascripts/funds/directives/[accounts_directives.js.coffee#L18](https://github.com/peatio/peatio/blob/master/app/assets/javascripts/funds/directives/accounts_directives.js.coffee#L18)

Should this line read:  
> $scope.currecny = @selectedCurrency

Or is it really:  
> $scope.curre**ncy** = @selectedCurrency

I'm reviewing a change I made to switch CNY with USD as the primary fiat currency for our test exchange and noticed that the line referenced above was picked up while searching across the project for occurrences of `cny`.

**Comment by brossi** [comment]
A related file that probably would potentially need to be looked at if the answer to the question above is, "it's a typo":

https://github.com/peatio/peatio/blob/master/db/migrate/20131208012814_fix_payment_address_currecny.rb

> class FixPaymentAddressCurre**cny** < ActiveRecord::Migration

**Comment by lgn21st** [comment]
@brossi :+1: Thank you for your report, fixed at 4c28ed978a0cdd9292b675ed9c825d1d01ac5f5e and dcb7ceec3c62a3598d8361e62f4689c106488f9f

**Comment by brossi** [comment]
Thank you, @lgn21st
