### ISSUE TITLE
请问如何解锁被锁定的金额？

### ISSUE THREAD

**Issue by windirt** [peatio/peatio#445]
我在提现测试中出现一个异常状态，金额被锁定，在后台找了半天没有找到可以解锁已锁定金额的地方

另外：这个异常状态的判定标准为什么？

**Comment by hpyhacking** [comment]
当提现时会有负责核对账户流水的程序来检查账户状态。

所以不能直接修改数据库表字段来试图增加或减少余额，需要使用`Account`的相关方法来操作账户。
