### ISSUE TITLE
Signup Goes to Blank Page

### ISSUE THREAD

**Issue by Gensia** [peatio/peatio#446]
Running a development version of Peatio in VMware seems to work well except clicking Signup on the Signup page leads the user to a blank page. In application.yml I commented out the line URL_HOST: peatio.dev so now instead of a blank page I get a page full of errors. So what to put in URL_HOST: to test Peatio in VMware?

**Comment by Gensia** [comment]
Tried http://0.0.0.0:3000 still get blank page.

**Comment by lgn21st** [comment]
@Gensia I've fixed on this commit: 94197af69e8d4ade467877472ff259f7e248ffc1

You need to modify your /etc/hosts and place the following line, let me know if it still not work.

```
127.0.0.1 peatio.dev
```

**Comment by hpyhacking** [comment]
Another choice use Pow start your peatio and powit to peatio.dev domain.
