### ISSUE TITLE
Mysql2::Error

### ISSUE THREAD

**Issue by splirow** [peatio/peatio#450]
I am getting this error

Mysql2::Error
Access denied for user '****'@'****' (using password: YES)

Extracted source (around line #11):
9
10
11
12
13
14
          
      env['HTTP_HOST'] = host
      env['HTTP_X_FORWARDED_HOST'] = host
      @app.call(env)
    end

    def host

Rails.root: /root/peatio

Application Trace | Framework Trace | Full Trace
lib/middleware/security.rb:11:in `call'
lib/middleware/i18n_js.rb:9:in `call'

**Comment by hpyhacking** [comment]
please reference deploy document fixed it.

BTW: peatio running with root is danger.
