### ISSUE TITLE
mailer_helper.rb

### ISSUE THREAD

**Issue by Gensia** [peatio/peatio#457]
Can someone please tell me if the changes to this file are acceptable and that I haven't broken Peatio 

module MailerHelper

  def assets_value_change_total(changes)
    total = changes.sum do |(currency, amount, value)|
      currency.code == 'cny' ? 0 : (value[0] || 0)
      currency.code == 'usd' ? 0 : (value[0] || 0)
      currency.code == 'gbp' ? 0 : (value[0] || 0)
    end
    pretty_change pretty_currency(total, 'cny'), total
    pretty_change pretty_currency(total, 'usd'), total
    pretty_change pretty_currency(total, 'gbp'), total
  end

**Comment by hpyhacking** [comment]
this's mail is for stat everyday exchange assets changed.

your are right if your don't want to show anyone currency changed in this mail.
