### ISSUE TITLE
is their a bug in deposit fiat currency form

### ISSUE THREAD

**Issue by cyclopse87** [peatio/peatio#458]
Hi I am trying to deposit the default cny currency , I think their is a bug in the  deposit funds form. There is no your name field, and when i try to drop down options for deposit accounts as well.

.

![image](https://cloud.githubusercontent.com/assets/8946973/8228866/d7d4894a-15ba-11e5-8fb9-33504f4bd9c1.png)

**Comment by gimmemoney** [comment]
'Your Name' is filled with the name provided in the step 'Verify Account'.
You have to add a bank account (click on 'Manage') to have it in the drop-down-list.

**Comment by cyclopse87** [comment]
Thanks for the help

**Comment by cyclopse87** [comment]
I got an unknown attribute error as soon as I filled out the form, I think I have a case of unmatched schema, or do you think its something else?

    ActiveRecord::UnknownAttributeError at /deposits/banks     
    unknown attribute:    fund_source app/controllers/concerns/deposits/ctrl_bankable.rb,
    line 10 ruby 5 included do 6 before_filter :fetch 7 end 8 9 
    def create > 10 @deposit =   model_kls.new(deposit_params) 11 12 if 
    @deposit.save 13 render nothing: true 14 else 15 render text: 
    @deposit.errors.full_messages.join, status: 403 ``` 
    App backtrace    app/controllers/concerns/deposits/ctrl_bankable.rb:10:in `create'

**Comment by tkembo** [comment]
Were you ever able to resolve this issue? I'm facing the same issue myself
