### ISSUE TITLE
Getting “ActiveRecord::UnknownAttributeError:

### ISSUE THREAD

**Issue by cyclopse87** [peatio/peatio#459]
I am running into this error when filling out the deposit form for CNY currency. I have checked to make sure that I ran rake db:migrate but no luck.

    ActiveRecord::UnknownAttributeError - unknown attribute: fund_source:
      activerecord (4.0.12) lib/active_record/attribute_assignment.rb:47:in `rescue in _assign_attribute'
      activerecord (4.0.12) lib/active_record/attribute_assignment.rb:42:in `_assign_attribute'
      activerecord (4.0.12) lib/active_record/attribute_assignment.rb:29:in `block in assign_attributes'
      activerecord (4.0.12) lib/active_record/attribute_assignment.rb:23:in `assign_attributes'
      activerecord (4.0.12) lib/active_record/core.rb:469:in `init_attributes'
      activerecord (4.0.12) lib/active_record/core.rb:185:in `initialize'
      enumerize (0.8.0) lib/enumerize/base.rb:48:in `initialize'
      activerecord (4.0.12) lib/active_record/inheritance.rb:30:in `new'
      app/controllers/concerns/deposits/ctrl_bankable.rb:10:in `create'
      actionpack (4.0.12) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
      actionpack (4.0.12) lib/abstract_controller/base.rb:189:in `process_action'
      actionpack (4.0.12) lib/action_controller/metal/rendering.rb:10:in `process_action'
      actionpack (4.0.12) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
     activesupport (4.0.12) lib/active_support/callbacks.rb:513:in 

 I'm a bit of a Rails noob, so it could be something simple.

**Comment by tkembo** [comment]
Just curious, were you ever able to resolve this issue? I'm having the same issue myself

**Comment by hpyhacking** [comment]
#471 fixed
