### ISSUE TITLE
Possible replacement of pusher?

### ISSUE THREAD

**Issue by lemial** [peatio/peatio#460]
Tell me what you can replace pusher? Maybe there is some kind of local solution?

**Comment by tkembo** [comment]
I could never find documentation on what pusher really does. What does pusher do exactly?

**Comment by arruah** [comment]
try this. 
What is happened with peatio.com? Is this project closed?

**Comment by homakov** [comment]
@lemial try slanger, it is pusher compatible

**Comment by valuead** [comment]
yes

**Comment by hpyhacking** [comment]
@homakov +1
slanger is right choose to replace pusher.

@arruah
please read https://github.com/peatio/peatio/releases/tag/v0.1.1
