### ISSUE TITLE
I can't apply cash request 

### ISSUE THREAD

**Issue by netwareboss** [peatio/peatio#461]
When i  try to apply a fund request

I always got this error!!! Is someone can help me???

Thanks a lot^^  

Here is my log output:

I, [2015-07-07T13:24:49.394544 #7415]  INFO -- : Started POST "/deposits/banks" for 223.136.173.55 at 2015-07-07 13:24:49 +0800
I, [2015-07-07T13:24:49.405113 #7415]  INFO -- : Processing by Private::Deposits::BanksController#create as HTML
I, [2015-07-07T13:24:49.405278 #7415]  INFO -- :   Parameters: {"deposit"=>{"account_id"=>3, "member_id"=>2, "currency"=>"cny", "amount"=>7778, "fund_source"=>2}, "bank"=>{"deposit"=>{"account_id"=>3, "member_id"=>2, "currency"=>"cny", "amount"=>7778, "fund_source"=>2}}}
I, [2015-07-07T13:24:49.432514 #7415]  INFO -- : Completed 500 Internal Server Error in 27ms
F, [2015-07-07T13:24:49.434844 #7415] FATAL -- :
ActiveRecord::UnknownAttributeError (unknown attribute: fund_source):
  app/controllers/concerns/deposits/ctrl_bankable.rb:10:in `create'
  lib/middleware/security.rb:11:in `call'

**Comment by alberthendriks** [comment]
I'd love to understand this framework better. I don't understand why neither
./app/api/api_v2/entities/deposit.rb nor
./app/models/deposit.rb
have fund_source.

**Comment by netwareboss** [comment]
ctrl_bankable.rb
 
28       @account = current_user.get_account(channel.currency) 
29       @model = model_kls 
30       @fund_sources = current_user.fund_sources.with_currency(channel.currency)

**Comment by charnasol** [comment]
Did you have any issues getting the board quoting? If not what file did you set up to make sure it was streaming quotes?

**Comment by netwareboss** [comment]
So????

Vào Thứ Tư, ngày 22 tháng 7 năm 2015, charnasol <notifications@github.com>
đã viết:

**Comment by netwareboss** [comment]
What should I do ???

Vào Thứ Tư, ngày 22 tháng 7 năm 2015, charnasol <notifications@github.com>
đã viết:

**Comment by charnasol** [comment]
I was just asking a question as I need help with that. I have all configured but my bitcoin trade board won't quote and wondered if you had any issues with that. Sorry to bother you. 

James McEvoy
CEO

**Comment by netwareboss** [comment]
Work fine for me^^
I try to build a web site by myself,
Would you be my partner????


Josh
Bitcoin fond
Vào Thứ Tư, ngày 22 tháng 7 năm 2015, charnasol <notifications@github.com>
đã viết:

> I was just asking a question as I need help with that. I have all
> configured but my bitcoin trade board won't quote and wondered if you had
> any issues with that. Sorry to bother you.
>
>
> CEO
>
> > On Jul 22, 2015, at 5:41 AM, netwareboss <notifications@github.com

**Comment by charnasol** [comment]
I would gladly help you if you could tell me what file you executed to get the board working good for you. 
My trade board doesn't quote bitcoin prices and I need help with that.
I can help you if you help me

James McEvoy
CEO

**Comment by netwareboss** [comment]
Yup^^ do you have email ?????
My email:netwareboss@gmail.com
Vào Thứ Tư, ngày 22 tháng 7 năm 2015, charnasol <notifications@github.com>
đã viết:

> I would gladly help you if you could tell me what file you executed to get
> the board working good for you.
> My trade board doesn't quote bitcoin prices and I need help with that.
> I can help you if you help me
>
> James McEvoy
> CEO
>
> > On Jul 22, 2015, at 5:55 AM, netwareboss <notifications@github.com

**Comment by netwareboss** [comment]
Welcome to visit my website,http://www.x-coins.com

Vào Thứ Tư, ngày 22 tháng 7 năm 2015, charnasol <notifications@github.com>
đã viết:

> I would gladly help you if you could tell me what file you executed to get
> the board working good for you.
> My trade board doesn't quote bitcoin prices and I need help with that.
> I can help you if you help me
>
> James McEvoy
> CEO
>
> > On Jul 22, 2015, at 5:55 AM, netwareboss <notifications@github.com

**Comment by charnasol** [comment]
I just replied direct 
Can you send me file name of which one will start and keep the board running and executing constantly:
And let me know what you need. Be glad to partner and help

James McEvoy
CEO

**Comment by netwareboss** [comment]
I just running as docment teach me ^^
You can go step by step by docs

Josh
Vào Thứ Tư, ngày 22 tháng 7 năm 2015, charnasol <notifications@github.com>
đã viết:

> I just replied direct
> Can you send me file name of which one will start and keep the board
> running and executing constantly:
> And let me know what you need. Be glad to partner and help
>
> James McEvoy
> CEO
>
> > On Jul 22, 2015, at 5:59 AM, netwareboss <notifications@github.com

**Comment by charnasol** [comment]
I can't find any documents on the trade board itself as far as quoting.
And if you like, me and my team can help you customize. 
Does your board quote pricing?

James McEvoy
CEO

**Comment by netwareboss** [comment]
I don't know.....but seems work fine for me now .... I have not test it yet
^^

Vào Thứ Tư, ngày 22 tháng 7 năm 2015, charnasol <notifications@github.com>
đã viết:

> I can't find any documents on the trade board itself as far as quoting.
> And if you like, me and my team can help you customize.
> Does your board quote pricing?
>
> James McEvoy
> CEO
>
> > On Jul 22, 2015, at 6:08 AM, netwareboss <notifications@github.com

**Comment by tkembo** [comment]
I'm just curious as to whether you were able to resolve this? I'm having the same issue myself

**Comment by netwareboss** [comment]
Yes,I do^^ take a look at my website http://www.x-coins.com

Vào Thứ Hai, ngày 14 tháng 9 năm 2015, Tawanda Kembo <
notifications@github.com> đã viết:

**Comment by tkembo** [comment]
How did you fix it? did you make changes to the controller or the model? or the database? please help

**Comment by netwareboss** [comment]
i didn't fix it!! Just disable it on source code^^

2015-09-14 22:44 GMT+08:00, Tawanda Kembo <notifications@github.com>:

**Comment by hpyhacking** [comment]
I fixed
