### ISSUE TITLE
peatio是否已经停止更新了？

### ISSUE THREAD

**Issue by summm** [peatio/peatio#465]
已经好久没有更新过了，是停止了这个项目了吗？
之前说的简单增减新币种等都不会再进行了吗？

**Comment by valuead** [comment]
English??

**Comment by mikoicc** [comment]
现在的模式有点变化，会由云币反推发展貔貅项目，而不是原来的单独对貔貅项目改进。

简单的增减币种在开发中呢。

在 2015年7月28日 下午1:14，summm <notifications@github.com>写道：

**Comment by hpyhacking** [comment]
please read v0.1.1 release 
https://github.com/peatio/peatio/releases/tag/v0.1.1
