### ISSUE TITLE
What is the figaro gem used for? Will anything break if I remove that gem

### ISSUE THREAD

**Issue by tkembo** [peatio/peatio#467]
I keep getting the following warning when i run a command and it's annoying:

```
current/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 60 was converted to "60". (StandardWarning)
```

I'm thinking that one way to getting rid of the error would be to remove the figaro gem but I can't see what it's used for

**Comment by hpyhacking** [comment]
figaro use to config application when running, all the `ENV['foo']` is support for figaro gem.

https://github.com/laserlemon/figaro
