### ISSUE TITLE
 compile error gem 'unread‘

### ISSUE THREAD

**Issue by microlost** [peatio/peatio#468]
got this error when run "bundle install" in Step 9: Configure Peatio

There was an error parsing `Gemfile`: compile error - syntax error, unexpected ':', expecting $end
gem 'unread', github: 'poshboytl/unread'
                     ^. Bundler cannot continue.

 #  from /home/ubuntu/peatio/Gemfile:68
 #  -------------------------------------------
 #  gem 'twilio-ruby', '~> 3.11'
 >  gem 'unread', github: 'poshboytl/unread'
 #  gem 'carrierwave', '~> 0.10.0'
 #  -------------------------------------------

**Comment by mikoicc** [comment]
this problem is fixed, please bundle with new Gemfile.

2015-08-29 1:18 GMT+08:00 microlost <notifications@github.com>:

**Comment by hpyhacking** [comment]
a2f2cf60ce7e12a12076815e85e56ddf4eacf858 fixed
