### ISSUE TITLE
NoMethodError: undefined method `id' for nil:NilClass

### ISSUE THREAD

**Issue by microlost** [peatio/peatio#469]
ubuntu@VM-197-127-ubuntu:~/peatio$ bundle exec rake db:setup --trace
** Invoke db:setup (first_time)
** Invoke db:schema:load_if_ruby (first_time)
** Invoke db:create (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:create
peatio_development already exists
peatio_test already exists
** Invoke environment (first_time)
** Execute environment
rake aborted!
NoMethodError: undefined method `id' for nil:NilClass
/home/ubuntu/peatio/spec/factories/payment_addresses.rb:11:in `block (3 levels) in <top (required)>'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/trait.rb:12:in `instance_eval'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/trait.rb:12:in `initialize'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/definition_proxy.rb:161:in `new'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/definition_proxy.rb:161:in `trait'
/home/ubuntu/peatio/spec/factories/payment_addresses.rb:8:in `block (2 levels) in <top (required)>'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/syntax/default.rb:18:in `instance_eval'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/syntax/default.rb:18:in `factory'
/home/ubuntu/peatio/spec/factories/payment_addresses.rb:4:in `block in <top (required)>'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/syntax/default.rb:49:in `instance_eval'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/syntax/default.rb:49:in `run'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/syntax/default.rb:7:in `define'
/home/ubuntu/peatio/spec/factories/payment_addresses.rb:3:in `<top (required)>'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:223:in `load'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:223:in `block in load'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:223:in `load'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/find_definitions.rb:20:in `block (2 levels) in find_definitions'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/find_definitions.rb:19:in `each'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/find_definitions.rb:19:in `block in find_definitions'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/find_definitions.rb:15:in `each'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.3.0/lib/factory_girl/find_definitions.rb:15:in `find_definitions'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl_rails-4.3.0/lib/factory_girl_rails/railtie.rb:21:in `block in <class:Railtie>'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:36:in `call'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:44:in `each'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.0.12/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:30:in `instance_exec'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:30:in `run'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `call'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:54:in `run_initializers'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.0.12/lib/rails/application.rb:215:in `initialize!'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.0.12/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/ubuntu/peatio/config/environment.rb:5:in `<top (required)>'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `require'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `block in require'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `require'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.0.12/lib/rails/application.rb:189:in `require_environment!'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.0.12/lib/rails/application.rb:260:in `block in run_tasks_blocks'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/home/ubuntu/.rbenv/versions/2.2.1/bin/rake:33:in `<main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => environment

**Comment by mikoicc** [comment]
please confirm BTC in your config/currencies.yml config because the
db:setup make btc to default market coin.

2015-08-29 3:29 GMT+08:00 microlost <notifications@github.com>:

**Comment by hpyhacking** [comment]
you can rename all `config/*.example` file for ensure `db:setup` and other setup.
