### ISSUE TITLE
可能是RabbitMQ没有配置好

### ISSUE THREAD

**Issue by microlost** [peatio/peatio#476]
自己用peatio源码自己搭建交易所研究用，现在还有些问题：
1.交易大厅无法自动刷新（Pusher账号都填写好了）
2.手机验证码发不出去了
3.提现失败（但是充值成功）

总感觉是RabbitMQ的问题，要么消息没有进入消息队列，要么进入队列后没有响应

**Comment by hpyhacking** [comment]
PEATIO 需要使用 ./bin/rake daemons:start 启动一些守护进程，而有些守护进程是 RabbitMQ 的消息处理端，所以 RabbitMQ 同时也要启动。

**Comment by microlost** [comment]
目前从后台看所有的守护进程都已经是running状态，是不是RabbitMQ的消息处理端的守护进程需要独立启动，该守护进程的名字叫啥

**Comment by 9cat** [comment]
我也遇到同样的问题·， @microlost 最后解决了吗？  @hpyhacking
