### ISSUE TITLE
Funds Withdraw 

### ISSUE THREAD

**Issue by melmali2828** [peatio/peatio#484]
Hi, btc Withdraw or bank Withdraw error.

![image](https://cloud.githubusercontent.com/assets/14098096/10904861/f8e74e4e-821e-11e5-849f-21646444b639.png)

![image](https://cloud.githubusercontent.com/assets/14098096/10904890/24ae1b48-821f-11e5-8438-36dc06f141af.png)

**Comment by melmali2828** [comment]
ok,

vim app/models/concerns/fund_sourceable.rb

![image](https://cloud.githubusercontent.com/assets/14098096/11166115/9a5922de-8b2f-11e5-9f4a-a7b23862acdd.png)

**Comment by microlost** [comment]
it will bring another bug when deposit
ActiveRecord::UnknownAttributeError - unknown attribute: fund_source

**Comment by hrishikeshio** [comment]
The error disappeared but quick withdraw still does not work.

**Comment by scotcoin** [comment]
Maybe try changing the currencies.yml file . In the quick withraw max withdraw line to something larger than 0

**Comment by maurodelazeri** [comment]
fix #485
