### ISSUE TITLE
Email verification not working

### ISSUE THREAD

**Issue by saravanan95** [peatio/peatio#492]
How to make email verification work in development mode.

I also tried production mode but the site is not loading properly it's not showing images. Please give solution to make email verification work in development  mode.

**Comment by hrishikeshio** [comment]
In development mode, go to http://localhost:3000/mails to access your mails.

**Comment by saravanan95** [comment]
I can view the mails but the verification mail is not sent to the customer who just signed up

**Comment by hrishikeshio** [comment]
Its not working for me either. A temporary fix is to login as admin, go to admin panel and verify customers email address manually. It works on production though.
