### ISSUE TITLE
Can I change the admin email id ? I changed in application.yml and seeds.rb but no changes. How can i solve this

### ISSUE THREAD

**Issue by karthickms** [peatio/peatio#496]

**Comment by tkembo** [comment]
Yes you can. 

You edit it in `config/application.yml` on the line that starts with: `ADMIN:`

**Comment by karthickms** [comment]
I edit in this line but no changes.

**Comment by karthickms** [comment]
Normally, a new user email-id added in the config/application.yml on the line that starts with: ADMIN: .
It's working fine. Thanks
