### ISSUE TITLE
If change from development to production server for send the mail but .js.coffee is not working in all pages. How can I solve this

### ISSUE THREAD

**Issue by karthickms** [peatio/peatio#500]

**Comment by hrishikeshio** [comment]
Can you explain what is the problem in more details? you question makes no sense.

**Comment by karthickms** [comment]
My problem is :
For change the production mode not be reflect the updated coding js.coffee file in ror. Hope anybody provide the answer

**Comment by hrishikeshio** [comment]
try running
bundle exec rake assets:precompile  RAILS_ENV=production

**Comment by karthickms** [comment]
Hi @hrishikeshio 

I try this but it works as same. 

If I change the any one line of sample_file.js.coffee but is not updated in production server mode. Normally it works as before the updated

Thanks for response

**Comment by hrishikeshio** [comment]
You also need to restart your server after every change and run above command when in production mode.

**Comment by karthickms** [comment]
Hi @hrishikeshio

Our site is on live. So if I try this command (bundle exec rake assets:precompile RAILS_ENV=production ) any other problem occurs?

**Comment by hrishikeshio** [comment]
you need to stop the server, run this command and start it up again. The server will be down for a minute but no other problem.
You can clear your browser cache if the problem persists.

**Comment by karthickms** [comment]
I also clear the browser cache. And stop the server when change the files and run this command but no other changes it works as same

**Comment by karthickms** [comment]
I found the solution. In cache file, updated my new coding after that its working fine
