### ISSUE TITLE
Ubuntu Email configuration

### ISSUE THREAD

**Issue by jcantalogo** [peatio/peatio#503]
I successfully finished the configuration peatio application ubuntu machine and try to test the application have not successfully sending email or sms to Brazil. What I have to do to be able to test these features? Grateful.

**Comment by hrishikeshio** [comment]
use mailgun for smtp. mailgun.com
for sms you need a twilio account. use these settings in config.yml

**Comment by jcantalogo** [comment]
Thank you ver much. What i have to do to configure Mailgun? What config files i need to update? And How?Tks again


Enviado do meu smartphone Samsung Galaxy.<div>
</div><div>
</div><div>-------- Mensagem original --------</div><div>De: Hrishikesh Huilgolkar <notifications@github.com> </div><div>Data: 10/03/2016  04:16  (GMT-03:00) </div><div>Para: peatio/peatio <peatio@noreply.github.com> </div><div>Cc: jcantalogo <jcantalogo@outlook.com> </div><div>Assunto: Re: [peatio] Ubuntu Email configuration (#503) </div><div>
</div>
use mailgun for smtp. mailgun.com
for sms you need a twilio account. use these settings in config.yml

---

**Comment by jcantalogo** [comment]
I setup production and review my application.yml and email is working fine. Tks a lot. 
BUT I am deploying this exchange in Brazil and Twillio does not have SMS service to brazilian numbers. There is any other service like that works with braziian SMS ?

**Comment by eric-tsoi** [comment]
I am using mailgun with the al the necessary settings but Peatio doesn't seem to be sending anything nor giving any errors. Can anyone point me to the code where the email verification code is and how i can see if the what the actionmail is doing?  Greatly appreciated.
