### ISSUE TITLE
Email configuration

### ISSUE THREAD

**Issue by jcantalogo** [peatio/peatio#505]
i create a account in MAILGUN and test it in my server using swaks command and it works !
But i input the information in application.yml file and it does not work. could anybody help me ?? 

This command works:
./swaks --auth \
        --server smtp.mailgun.org:587 \
        --au postmaster@sandboxblablabla911.mailgun.org \
        --ap ????????????????????? \
        --to xxxxxxx@yyy.com.br \
        --h-Subject: "Hello" \
        --body "Testing some Mailgun awesomness!"

Configuration on application.yml:
  SMTP_PORT: 587
  SMTP_DOMAIN: sandboxfdbda7d5b99841dfb4c7000b94cae911.mailgun.org
  SMTP_ADDRESS: smtp.mailgun.org
  SMTP_USERNAME: postmaster@sandboxfdbda7d5b99841dfb4c7000b94cae911.mailgun.org
  SMTP_PASSWORD: xxxxxxxxxxxxxx

**Comment by jcantalogo** [comment]
All is working Well now. I deploy production environment and review application.yml and it works correctly.

**Comment by ShadowMyst** [comment]
Did you make any changes to the settings for it to work?
