### ISSUE TITLE
unknown column while 'bundle exec rake db:setup'

### ISSUE THREAD

**Issue by ldh2068vip** [peatio/peatio#521]
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'taggings_count' in 'field list': UPDATE `tags` SET `taggings_count` = COALESCE(`taggings_count`, 0) + 1 WHERE `tags`.`id` = 1
/Users/kevin/GitHub/peatio/db/seeds.rb:21:in `<top (required)>'
/Users/kevin/.rbenv/versions/2.2.1/bin/bundle:23:in `load'
/Users/kevin/.rbenv/versions/2.2.1/bin/bundle:23:in `<main>'
Mysql2::Error: Unknown column 'taggings_count' in 'field list'
/Users/kevin/GitHub/peatio/db/seeds.rb:21:in `<top (required)>'
/Users/kevin/.rbenv/versions/2.2.1/bin/bundle:23:in `load'
/Users/kevin/.rbenv/versions/2.2.1/bin/bundle:23:in `<main>'
Tasks: TOP => db:setup => db:seed
(See full trace by running task with --trace)

there is no column taggings_count in table tags from schema.rb actually.

**Comment by ldh2068vip** [comment]
I reinstall twice more , this error is not reappear .

**Comment by cyzanfar** [comment]
Having the same issue. How to resolve?

**Comment by anibha88** [comment]
@cyzanfar This might help
https://stackoverflow.com/questions/23239578/after-upgrading-to-rails-4-1-acts-as-taggable-on-is-not-working
You have to run
rake acts_as_taggable_on_engine:install:migrations

**Comment by scatterp** [comment]
@cyzanfar  the answer is right above your question simply reinstall and this time dont migrate the db 
better use the script from my repo and dont do anything it will do it all for you :)
