### ISSUE TITLE
Where to check Withdrawal errors? Withdrawal does not work

### ISSUE THREAD

**Issue by vetal20600** [peatio/peatio#551]
I am trying to add alternative cryptocurrency. Everything is fine when I put deposit.
But when I am trying to withdraw nothing happened.
No errors, no withdrawal. Nothing happens event if I press on "submit" without selecting amount/google secure password (I assume error message may appear).
![screen shot 2017-03-01 at 09 27 29](https://cloud.githubusercontent.com/assets/4103746/23450023/9407925c-fe61-11e6-939d-1b39459e5456.png)

I guess I have to add source code. But it is not obvious where.
I have added class mycoin.rb to /doc/proj/Peatio/app/models/withdraws:
```
module Withdraws
  class Mycoin < ::Withdraw
    include ::AasmAbsolutely
    include ::Withdraws::Coinable
    include ::FundSourceable
  end
end
```
But it didn't help. Any suggestions?

**Comment by wujinxing** [comment]
cd /peatio/log
tail -f peaio:amqp:noification.out

**Comment by vetal20600** [comment]
Is there any guide how to set up withdrawal?
Similar to https://github.com/peatio/peatio/blob/master/doc/currency.md? 

Only on error I see in log is 
`E, [2017-02-28T19:15:16.108720 #19899] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)`
But this issue was there before my tries to withdraw.

**Comment by vetal20600** [comment]
Update. There are two more:
`E, [2017-02-28T19:15:16.123148 #19899] ERROR -- : Permission to send an SMS has not been enabled for the region indicated by the 'To' number: +[some_number]. (Twilio::REST::RequestError)`

```
/home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `run_loop'
E, [2017-02-28T19:15:16.123204 #19899] ERROR -- : read would block (OpenSSL::SSL::SSLErrorWaitReadable)
```
But I am using google pass to authentificate. Seems like this issue is not related to withdrawal too.
I am guessing this is my problem:
`E, [2017-02-28T19:15:16.126079 #19899] ERROR -- : undefined method `parameters' for nil:NilClass (NoMethodError)`
Or this:
```
E, [2017-03-01T08:12:24.708012 #28028] ERROR -- : stream closed (IOError)

E, [2017-03-01T08:12:24.708151 #28028] ERROR -- : failed to allocate memory (NoMemoryError)

E, [2017-03-01T08:12:24.708198 #28028] ERROR -- : stack level too deep (SystemStackError)

E, [2017-03-01T08:12:24.708341 #28028] ERROR -- : exception reentered (fatal)

E, [2017-03-01T08:12:24.715483 #28028] ERROR -- : Value will be available once the pipeline executes. (Redis::FutureNotReady)

E, [2017-03-01T08:12:24.726396 #28028] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
```
