### ISSUE TITLE
Useful Commands for Newbies

### ISSUE THREAD

**Issue by Gensia** [peatio/peatio#560]
Clear Database & Repopulate:
     bundle exec rake db:reset
     bundle exec rake db:setup

Clean and Restart Webserver:
     bundle exec rake daemons:stop
     bundle exec rake assets:clean
     bundle exec rake assets:clobber
     bundle exec rake tmp:clear
     bundle exec rake tmp:create 
     bundle exec rake assets:precompile
     bundle exec rake daemons:start
     sudo service nginx restart 
     sudo service rabbitmq-server restart

Bitcoin Commands:
     Determine amount of downloaded blockchain: bitcoin-cli getblockcount
     Compare current size here: https://blockchain.info/q/getblockcount
     bitcoin-cli start
     bitcoin-cli stop
     bitcoin-cli getnetworkinfo
     bitcoin-cli getblockchaininfo
     bitcoin-cli getwalletinfo
     bitcoin-cli getnewaddress   (get new address if one is not assigned)
     bitcoin-cli help

Missing Commands from "Deploy production server on Ubuntu 14.04" Doc:
     bundle exec rake daemons:start
     sudo -s
     bundle exec rails server

**Comment by ShadowMyst** [comment]
Thank you very much, I solved a big problem with "config.assets.compile" and I was able to start the server
