### ISSUE TITLE
Mysql2::Client::SECURE_CONNECTION

### ISSUE THREAD

**Issue by felipecaldas** [peatio/peatio#562]
Hi, 
Following the Ubuntu step by step and trying to run the MySQL database config step:

vim config/database.yml

# Initialize the database and load the seed data
bundle exec rake db:setup

Getting the following error

NameError: uninitialized constant Mysql2::Client::SECURE_CONNECTION

Makes me think that the ruby version cannot run Mysql2 but this is what I have:

root@af61091b4229:/usr/local/share/peatio# ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

Any ideas? Thanks

**Comment by felipecaldas** [comment]
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'mysql2'.
Gem Load Error is: uninitialized constant Mysql2::Client::SECURE_CONNECTION

to be exact

**Comment by muhammednagy** [comment]
duplicate #528

**Comment by muhammednagy** [comment]
you should close this issue

**Comment by felipecaldas** [comment]
The resolution on 528 does not work.

**Comment by muhammednagy** [comment]
show me the errors 
i fixed it :)

**Comment by felipecaldas** [comment]
I am at work now, but very happy to show you the issues. Would you be free for a Skype message chat sometime this week?

**Comment by muhammednagy** [comment]
Why Skype ?
Here is my website muhnagy.com
You can send me email or chat with me on Facebook

**Comment by felipecaldas** [comment]
Sounds good, I'll get in touch soon.

**Comment by felipecaldas** [comment]
I was finally able to figure this out... before running the `bundle install` command I did:

```
bundle config build.bunny --with-cppflags=-I/usr/local/opt/openssl/include
bundle config build.eventmachine --with-cppflags=-I/usr/local/opt/openssl/include
```

The problem was that, not sure why, bundler could not find the openssl libraries. So had to point there.
That's in a Mac.

Hope this helps others

**Comment by felipecaldas** [comment]
Actually, sorry, that didnt fix it.
Still having the same issue when running bundle exec rake db:setup

The digging continues...

**Comment by muhammednagy** [comment]
you can check my fork it's working on it
https://github.com/muhammednagy/peatio

**Comment by muhammednagy** [comment]
make sure to remove to install rbenv or rvm and use 2.2.1

**Comment by felipecaldas** [comment]
cool Muhammed, thanks
going to try this now

**Comment by felipecaldas** [comment]
The error I now get is:

fcaldas@192-168-1-13:~/projects/peatio/src/peatio$ bundle exec rake db:setup
rake aborted!
Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 6 column 3
/Users/fcaldas/projects/peatio/src/peatio/config/application.rb:15:in `<module:Peatio>'
/Users/fcaldas/projects/peatio/src/peatio/config/application.rb:14:in `<top (required)>'
/Users/fcaldas/projects/peatio/src/peatio/Rakefile:5:in `require'
/Users/fcaldas/projects/peatio/src/peatio/Rakefile:5:in `<top (required)>'
/Users/fcaldas/.rbenv/versions/2.2.1/bin/bundle:23:in `load'
/Users/fcaldas/.rbenv/versions/2.2.1/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
fcaldas@192-168-1-13:~/projects/peatio/src/peatio$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin15]

Installed everything, except the Bitcoin Core. Any ideas, Muhammed? Thanks

**Comment by felipecaldas** [comment]
Oh damn, I found what the problem was. Too many spaces on the application.yml file
This helped me out https://github.com/ruby/psych/issues/190

alright, let me continue

**Comment by felipecaldas** [comment]
Hoooray! It's working!!! Thanks for all your help, Muhammed! Really appreciate that. Inshala
Now, there's much much much more work ahead of me, to get this working just the way I want
