### ISSUE TITLE
Pusher

### ISSUE THREAD

**Issue by ShadowMyst** [peatio/peatio#577]
In the application.yml the following data is put
PUSHER_APP: xxxxx
PUSHER_KEY: xxxxxx
PUSHER_SECRET: xxxxxx
PUSHER_HOST: api.pusherapp.com
PUSHER_PORT: 80

But in the page of pusher there is an extra data

Cluster = "us2"

Where is it placed?

**Comment by ShadowMyst** [comment]
I already got the solution thanks

**Comment by vetal20600** [comment]
you can skip this setting in some cases.

**Comment by ShadowMyst** [comment]
If but I really failed the Pusher and I never connect, muhammed told me by mail that it is configured on host as api-us2.pusher.com.

**Comment by vetal20600** [comment]
as I see there is no cluster preference in source code of peatio. so it (pusher protocol) uses default cluster if cluster isn't defined.

**Comment by ShadowMyst** [comment]
Then when you change the configuration to api-us2.pusher.com. That's when I really worked

**Comment by vetal20600** [comment]
I think this address is default api address for chosen pusher zone (zone defines a cluster). that is why it works.

**Comment by egg6909** [comment]
hello, i changed yml files. but it is not working. can i more modify code for pusher?

PUSHER_HOST: api-ap1.pusher.com
