### ISSUE TITLE
Any news on the project? Seems to be dead...

### ISSUE THREAD

**Issue by Overtorment** [peatio/peatio#580]
subj

**Comment by ShadowMyst** [comment]
The original project is apparently discontinued, however you can follow the fork of muhammed or mine that somehow we are giving continuity.

My fork is in Spanish

**Comment by Overtorment** [comment]
Thanks @ShadowMyst 

I've checked forks, and looks like those are the active ones:

https://github.com/blueplanet/peatio
https://github.com/muhammednagy/peatio
https://github.com/ShadowMyst/peatio
