### ISSUE TITLE
Hiring Dev to help me Setup Peatio

### ISSUE THREAD

**Issue by Raunchard** [peatio/peatio#604]
Hi,
I am looking for help setting up Peatio (muhammednagy fork with Ethereum) on Azure.
Additionally it would be nice if you could explain to me how to customize Peatio. I am a software developer myself, but I need an Expert to show me all the pitfalls and things I need to consider,
and help me hit the ground running.

The plan is to set up the basic framework within a weekend. After that you could possibly join as a consultant and I would of course pay you for your time and expertise.
Cheers

**Comment by MaffeProg** [comment]
Can I email you?

**Comment by Raunchard** [comment]
Would love to hear from you!
Am 13.09.2017 23:15 schrieb "MaffeProg" <notifications@github.com>:

**Comment by Raunchard** [comment]
If you have any Questions, shoot. Does not have to be Azure. Just something that scales well for the future.
Best Regards.

**Comment by MaffeProg** [comment]
How can I send you a message?

**Comment by Raunchard** [comment]
Contact me at Reinhard.Zach@Gmail.com
Thanks!
Am 14.09.2017 20:07 schrieb "MaffeProg" <notifications@github.com>:
