### ISSUE TITLE
bitcoind problem

### ISSUE THREAD

**Issue by eduinvestor** [peatio/peatio#611]
Hello!

I'm trying to edit the bitcoin.config file but I can't do it since I have not permission because I'm not the owner. How can I gain access to edit this file? Or is there another way to do it?

**Comment by MaffeProg** [comment]
You don't have root access?

**Comment by eduinvestor** [comment]
I'm not authorized to edit bitcoind folder (that includes bitcoin.config)
I have the root password but I don't know how to gain access.

I've tried to do a "folder sharing" but I get this error: error 255: net usershare add: cannot share path /usr/share/doc/bitcoind as we are restricted to only sharing directories we own.
	Ask the administrator to add the line "usershare owner only = false" 
	to the [global] section of the smb.conf to allow this.

**Comment by MaffeProg** [comment]
https://github.com/peatio/peatio/blob/master/doc/deploy-production-server.md

setup a production server files are located within the users access.

Else you need a full access vps. Which I recommend because shared hosting is really bad
