### ISSUE TITLE
Withdraw Issue - Case inside

### ISSUE THREAD

**Issue by ShiningBomb** [peatio/peatio#614]
Alice and Bob both are peatio members
1. Deposit btc to Alice
2. Alice put btc sell order
3. Bob deposit cny
4. Bob buy Alice btc
5. Bob Withdraw btc back to Alice

The withdraw is always got rejected. But if I withdraw it to external bitcoin address it works ok.

I thought it was liability proof problem but, I run it manually still can't withdraw that case.

**Comment by MaffeProg** [comment]
Sorry I don't really understand you. Step 4 withdraw back? Withdraw is withdraw it doesn't matter to which address.

**Comment by ShiningBomb** [comment]
Remember you can put bitcoin address when you withdraw? Using Bob's account put Alice's bitcoin address on it.

**Comment by ShiningBomb** [comment]
Anyone know how to debug models/worker/withdraw_coin.rb? I put breakpoint but never hit regardless it is success or fail. I'll happy to contribute the fix for this after.

**Comment by ShiningBomb** [comment]
Fixed this defect. Will put pull request soon to muhammednagy branch.

**Comment by rhombl4** [comment]
The way you did it is wrong. "Else" condition that you removed helps to avoid additional commissions of bitcoin-network. In fact, you just sending coins inside your account, i.e. waste of coins. 
You should implement an additional functionality which will transfer funds between balances of those users without using bitcoin-service at all.

**Comment by rhombl4** [comment]
The breakpoints are not working because daemons detaches from stdin

**Comment by ShiningBomb** [comment]
Yes, i completely understand that. But, customers are expecting to pay when they withdraw so it is not a big issue compared to not being able to send bitcoin to the wallet in the same exchange.

And how to breakpoint that daemons? I'm willing to contribute more so that would be helpful.

**Comment by rhombl4** [comment]
It looks like you understand me a little bit wrong.. In the condition that you changed, you could replace rejecting withdraw to another method which will move bitcoins between users accounts inside the exchange. The method is something like current_user.btc_account.transfer_coins_to another_account(account: account.find_by(btc_wallet_address)).

In purposes of debugging daemons, I was using the output of interesting variables into the Rails logger.
