### ISSUE TITLE
Buy/sell orders and fiat deposit are not updated after submitting

### ISSUE THREAD

**Issue by rgcosta** [peatio/peatio#629]
Guys,

I really appreciate any help to solve this issue.

My buy/sell orders and fiat deposit are not updated on the screen after submitting. They only get updated after browser refresh with F5.

I guess this is the same problem. I already double checked my pusher settings (default key which came with peatio), all daemons are running (according to the admin panel) and production.log but there is no clue of the problem source. I reinstalled peatio twice from scratch and nothing changed.

The only possible problem source that I got from log is the bellow log. This is showed in many different log files, except production.log but I don't know if it's related to my problem and I even don't know what it means.

```
E, [2017-10-18T00:51:52.022263 #13313] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `read_nonblock'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `block in read_fully'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `loop'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `read_fully'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/transport.rb:199:in `read_next_frame'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:63:in `run_once'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:33:in `block in run_loop'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `loop'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `run_loop'
```

Please, guys, any idea what else should I check? firewall rules? directory permissions?

Thanks in advanced

**Comment by wirelessjeano** [comment]
Did you remember to put the current user in the sudo group?

"sudo usermod -a -G sudo deploy"

Was having the same issue, this fixed it for me.

**Comment by scatterp** [comment]
@wirelessjeano 
can you describe your code base which git repo which commit this happened at?

**Comment by wirelessjeano** [comment]
Its not a bug in the code, it has to do with setting up the server environment correctly. If the user under which the rake daemons are running is not part of the sudo group, the rake daemons do not have sufficient permissions to make file changes by themselves (*.pid - everything in linux is a file).

**Comment by rgcosta** [comment]
@wirelessjeano 
I've put this command exactly it is in the installation doc from Muhammednagy fork. 

How can I be sure if my user is part of the sudo group? I tried this below command and it seems fine, right?

```
deploy@bitexchange1:~$ getent group sudo
sudo:x:27:ubuntu,deploy
```

**Comment by wirelessjeano** [comment]
@rgcosta, I am not sure what that code does. See #1 in https://github.com/muhammednagy/peatio/blob/master/doc/deploy-production-server.md

**Comment by rgcosta** [comment]
I did that, but nothing changed.

Is there anything else that I can do or check?

**Comment by rgcosta** [comment]
It worked. Finally!!! After redoing the command as said by wirelessjeano, I needed to restart the webserver and all daemons. 

I also needed to change the [application controller file ](https://github.com/peatio/peatio/blob/master/app/controllers/application_controller.rb) in the line 124, from:

`wsHost:    ENV['PUSHER_HOST']      || 'ws.pusherapp.com',`

To:

`wsHost:    'ws-us2.pusher.com',`

@wirelessjeano thank you very much for your help.
