### ISSUE TITLE
Question Regarding Rails-Observer Failure

### ISSUE THREAD

**Issue by HysMagus** [peatio/peatio#631]
Hi All,
I was looking to get some help on working with rails-observer version 0.1.5 on peatio scatterp's branch.
I am running on ubuntu  16.04 
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
When I Attempt the command 
'bundle install --without development test --path vendor/bundle'
I receive the output
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Using rake 10.5.0
Using aasm 3.4.0
Using i18n 0.8.6
Using minitest 4.7.5
Using multi_json 1.12.2
Using thread_safe 0.3.6
Using tzinfo 0.3.53
Using builder 3.1.4
Using erubis 2.7.0
Using rack 1.5.5
Using mime-types 1.25.1
Using activerecord-deprecated_finders 1.0.4
Using arel 4.0.2
Using public_suffix 3.0.0
Using amq-protocol 2.2.0
Using eventmachine 1.0.9.1
Using angularjs-rails 1.3.15
Using awesome_print 1.8.0
Using ice_nine 0.11.2
Using bcrypt 3.1.11
Using rb-fsevent 0.10.2
Using ffi 1.9.18
Using thor 0.20.0
Using browser 0.8.0
Using bundler 1.15.4
Using cancancan 2.0.0
Using json 2.1.0
Using chronic 0.10.2
Using coffee-script-source 1.12.2
Using execjs 2.7.0
Using concurrent-ruby 1.0.5
Using cookiejar 0.3.3
Using currencies 0.4.2
Using daemons 1.2.4
Using structured_warnings 0.3.0
Using eco-source 1.1.0.rc.1
Using http_parser.rb 0.6.0
Using equalizer 0.0.11
Using request_store 1.3.2
Using hashie 3.5.6
Using multi_xml 0.6.0
Using kramdown 1.15.0
Using http_accept_language 2.1.1
Using httpclient 2.8.3
Using jwt 1.5.6
Using mysql2 0.3.21
Using phonelib 0.3.6
Using pusher-signature 0.1.8
Using rbtree 0.4.2
Using redis 3.3.3
Using rotp 3.3.0
Using tilt 2.0.8
Using temple 0.8.0
Using descendants_tracker 0.0.4
Using activesupport 4.0.13
Using rack-test 0.6.3
Using rack-accept 0.4.5
Using rack-mount 0.8.3
Using rack-attack 3.0.0
Using mail 2.6.6
Using rest-client 1.6.9
Using addressable 2.5.2
Using bunny 1.2.2
Using amqp 1.3.0
Using em-socksify 0.3.1
Using liability-proof 0.0.9
Using bcrypt-ruby 3.1.5
Using rb-inotify 0.9.10
Using figaro 1.1.1
Using whenever 0.9.7
Using coffee-script 2.4.1
Using uglifier 3.2.0
Using sprockets 3.7.1
Using countries 0.9.3
Using daemons-rails 1.2.1
Using rubytree 0.8.3
Using em-websocket 0.5.1
Using omniauth 1.2.2
Using twilio-ruby 3.16.1
Using pusher 1.3.1
Using redis-store 1.3.0
Using slim 3.0.8
Using axiom-types 0.1.1
Using coercible 1.0.0
Using active_hash 1.5.2
Using activemodel 4.0.13
Using enumerize 0.8.0
Using grape-entity 0.4.8
Using jbuilder 2.6.4
Using actionpack 4.0.13
Using em-http-request 1.1.5
Using sass-listen 4.0.0
Using eco 1.0.0
Using country_select 2.1.1
Using omniauth-identity 1.1.1
Using redis-rack 2.0.2
Using redis-activesupport 5.0.3
Using virtus 1.0.5
Using activerecord 4.0.13
Using carrierwave 0.10.0
Fetching rails-observers 0.1.5
Installing rails-observers 0.1.5
Using actionmailer 4.0.13
Using railties 4.0.13
Using sprockets-rails 2.3.3
Using easy_table 0.0.6
Using gon 5.2.3
Using kaminari 0.17.0
Using simple_form 3.1.1
Using sass 3.5.1
Using redis-actionpack 5.0.1
Using grape 0.7.0
Using acts-as-taggable-on 4.0.0
Using globalize 4.0.3
Using paper_trail 3.0.9
Using paranoid2 1.1.4
Using unread 0.4.0 from git://github.com/peatio/unread.git (at master@b8fa050)
Gem::InstallError: rails-observers requires Ruby version >= 2.2.2.
An error occurred while installing rails-observers (0.1.5), and
Bundler cannot continue.
Make sure that `gem install rails-observers -v '0.1.5'` succeeds before
bundling.

Would anyone be able to help me with this? I am really stuck and have reset my vps like a dozen times :sweat_smile: .

**Comment by GH0STL1N3R** [comment]
What is your current Ruby version? You can check this in the terminal with the command: `ruby -v`

**Comment by scatterp** [comment]
please use the gemfile and gemfile.lock from here https://github.com/muhammednagy/peatio/tree/e839bf2fa63e975835195a228ef88f6374d65a1b
and let me know if it solves your problem

**Comment by huszlulz** [comment]
Using unread 0.4.0 from git://github.com/peatio/unread.git (at master@b8fa050)
Gem::InstallError: rails-observers requires Ruby version >= 2.2.2.
An error occurred while installing rails-observers (0.1.5), and Bundler cannot continue.
Make sure that `gem install rails-observers -v '0.1.5'` succeeds before bundling.

In Gemfile:
  rails-observers

using ruby 2.2.1 ....  
i have same problem

**Comment by huszlulz** [comment]
thanks, already update the GemFile.. thanks., its working well now

**Comment by scatterp** [comment]
you can now install with one command i also sent you an add on google chat
please see readme for latest updates

**Comment by HysMagus** [comment]
Hi All!
I replaced the gemfile and I received this response:
An error occurred while installing mysql2 (0.3.21), and Bundler cannot
continue.
Make sure that `gem install mysql2 -v '0.3.21'` succeeds before bundling.
In Gemfile:
The log file outputted:
" -o conftest -I/include/universal-java1.8 -I/home/deploy/.rbenv/versions/jruby$
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: #include <ruby.h>
4: int main(int argc, char **argv)
5: {
6:   return 0;
7: }
/* end */

Thank you all for your awesome work! I really appreciate the assistance!

**Comment by huszlulz** [comment]
rm -rf GemFile GemFile.lock , copy gemfile and gemfile.lock, follow scatterp instructions.

**Comment by scatterp** [comment]
hi huslulz you can now just do this
Recently done / News

•Installer with minimal steps [RELEASE(https://github.com/scatterp/peatio/blob/master/install1.sh)] wget https://raw.githubusercontent.com/scatterp/peatio/master/install1.sh source install1.sh

NOTE: it is critical you launch this with "SOURCE" not "SH" not "BASH" etc NOTE2: less than 4GB of ram you should disable the line that reads bitcoind or you wont have enough memory to launch the page

**Comment by huszlulz** [comment]
If you in Ubuntu 16.04 no need use mysql5.6..

**Comment by huszlulz** [comment]
Thanks scatterp. My problem already fixed.  But I cannot sign in with github to communicate your IM .

**Comment by scatterp** [comment]
i added you on google talk to help you get signed in

**Comment by HysMagus** [comment]
that output remains the same after replacing Gem and Gem lock, I'm going to try resetting the install than running the installer again. Perhaps I messed something up while setting up. Let's see if it's a human error on my part :joy:
Thank you all!

**Comment by HysMagus** [comment]
Solution:
After resetting the device I was able to go through scatterp's repo once more, it was an issue in the version of sql installed which was corrected after the restart. The ISO file i was using had a different version of sql preinstalled. Thank you @scatterp @huszlulz @GH0STL1N3R !

**Comment by scatterp** [comment]
hysmagus keep us posted on your progress dont be a stranger :)
