### ISSUE TITLE
Understanding The Business Logic...

### ISSUE THREAD

**Issue by deepuleo** [peatio/peatio#641]
I am Developer but need to understand how it works.

1) How the Inventory in maintained in Peatio?
2) If some Buys 10 BTC from us and we only have 5 BTC then what we will do?
3) If we buy bitcoin and other cryptocurrencies and store them what happen's when prices drop down?
4) Are these all process automatic or we have to approve transaction's?
5) What if there is only seller not buyer or vice versa?

Regard's
Deepankar Joshi
+918824335106

**Comment by wildunne** [comment]
You don't seem to even understand what this is, it's essentially a wrapper around a matching engine. It's not a simple broker with a set price.

**Comment by scatterp** [comment]
these are not coding questions they are finance/security
1 don`t  hold any inventory on peatio money should be in a bank potentially as a usb key in a safe
2 you need an investor willing to cover the costs of the business
3 you win or lose depending on your investments in trading tech and human traders and risk management
4 you should approve everything!
5 your marketing and sales budget is to small..

**Comment by deepuleo** [comment]
Is their any blog or link where i can understand the Details @scatterp @wildunne

**Comment by deepuleo** [comment]
@wildunne can you please elaborate it more.

**Comment by wildunne** [comment]
If you want me to elaborate more, I can provide consultancy at a not very cheap rate. As has been mentioned these are business questions not code questions.

**Comment by wildunne** [comment]
Also what scatterp said isn't even correct, you shouldn't have liability unless you so wish

**Comment by deepuleo** [comment]
@wildunne add me at deepuleo_16 skype

**Comment by scatterp4** [comment]
wildunne that`s what mtGox said .. 
if you hold other peoples money you have liability`s to pay them back
its a pretty simple concept 
and if you provide consultancy you should be aware of these basics...

**Comment by scatterp4** [comment]
see also this from the readme
SECURITY KNOWLEDGE IS A REQUIREMENT.

Peatio cannot protect your customers when you leave your admin password 1234567, or open sensitive ports to public internet. No one can. Running an exchange is a very risky task because you're dealing with money directly. If you don't known how to make your exchange secure, hire an expert.

Features

Built-in Proof of Solvency Audit.
