### ISSUE TITLE
Working Ubuntu Server with Peatio configured (Demo)

### ISSUE THREAD

**Issue by xibalbatech** [peatio/peatio#648]
Hello,

Does an disk image exist with a working configured Peatio exchange? Would anyone be willing to share there hard work and provide an image file (iso.) of a working system? I am willing to write some documentation on using Peatio and contribute but configuration is setting me back. If this is an obscene request forgive me as I am new to git-hub. Thank you for your time.

Regards,

Jacob

**Comment by scatterp** [comment]
you can use my github http://github.com/scatterp/peatio you can:
use a 16.04 standard iso
adduser deploy
usermod -a -G deploy 
log out completely and back in
 wget install.sh 
source install.sh 

and your done ..

**Comment by xibalbatech** [comment]
I will give this a try. I successfully installed Peatio before but there were many obstacles with outdated repositories. I have since repurposed the server I installed it on. Hence why I thought it would be easier to find an image of a working configuration. Thanks for the prompt response.

-Jacob

**Comment by xibalbatech** [comment]
Worked flawlessly. Now I am trying to get the front-end looking a bit more like an exchange with charts and the like. I will review the documentation before I post an issue. Thanks again!

-Jacob
