### ISSUE TITLE
Pusher Error 1006

### ISSUE THREAD

**Issue by chuakwee** [peatio/peatio#655]
Hi, I am using the Google Cloud Ubuntu 14.0.1. I have setup the peatio site and can create account and logon. I am using my own pusher account, but i kept getting error: "Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":1006,"message":"Connection interrupted (0)"}}} application-89b9c8d2652301fa3c8f31f8e97d0d1f.js:156:1880".

Any idea why and steps to troubleshoot? Thank you.

**Comment by tihualong** [comment]
you can use a a standalone server ruby implementation of the Pusher protocol like slanger

**Comment by chuakwee** [comment]
Thanks, i will try slanger now.

**Comment by dkkoval** [comment]
@chuakwee are you using

**Comment by dkkoval** [comment]
@chuakwee are you using the account

**Comment by dkkoval** [comment]
@chuakwee are you using your own pusher account? Did you specify pusher cluster?

**Comment by chuakwee** [comment]
Hi @dkkoval, i first timer to Rails and not sure where to change the code for adding pusher cluster, what i did is i have created the Pusher app defaulted to the first cluster.

**Comment by sushilraghav** [comment]
@chuakwee I can help you. I am having a vast experience in Peatio, Crypto Currency exchange and trading platforms with FIAT currency based on Bitcoin, litecoin, Ethereum, XRP etc, Core Wallets and Daemons. I am having expertise in ICO ie Initial Coin Offering full system development, White Paper creation with full architecture and high level documentation, smart contract writing and many more skills.

My Skype : sushilraghav and email is admin@rensoftglobal.com

**Comment by dkkoval** [comment]
@chuakwee you can check our [fork](https://github.com/rubykube/peatio), we're upgrading lots of components there. You can also check our [demo](https://demo.peatio.tech) (contact me if you have any questions).

**Comment by scatterp** [comment]
@chuakwee - You need to use Ubuntu 16.04 and use my repo:
http://github.com/scatterp/peatio 
Its a one command install.

**Comment by taylorshuang** [comment]
@dkkoval ，thanks for your work!  I find you added only one coin: ripple, do you will add other coins?eth, zcash, etc.

**Comment by chuakwee** [comment]
Hi @dkkoval and @scatterp , I will try both forks. Thanks and will close this issue.

**Comment by dkkoval** [comment]
@taylorshuang yes, soon we will work on adding other most popular coins.
