### ISSUE TITLE
Add Monero coin

### ISSUE THREAD

**Issue by rahulkhairnarr** [peatio/peatio#656]
Hey guys, 
 I am looking to add Monero in peatio but unable to find proper documentation. Can any one tell me what things needed to add the coin. Any documentation or anything. 

Thanks.

**Comment by scatterp** [comment]
there is some partial documentation if you read through all the issues how ever its incomplete 
you can refer to muhammednagy`s repo and see how he added eth combined with the doc that will be a starting point past that you must know how to program...

**Comment by rahulkhairnarr** [comment]
thanks, i have done almost all thing. I stuck at generating new address with "translation missing: en.private.deposits.incubcoins.gen_address.require_transaction" error.

**Comment by rahulkhairnarr** [comment]
Getting ":sum=>#<BigDecimal:557c3b1b30e8,'0.0',9(18)>, :balance=>#<BigDecimal:557c3b1b37c8,'0.0',9(18)>, :locked=>#<BigDecimal:557c3b1e7708,'0.0',9(18)>, :coinable=>true" while opening admin panel

**Comment by rahulkhairnarr** [comment]
Successfully added cryptonote based coin.. Thanks all of you for such support.

**Comment by EarlVadim** [comment]
Sorry, What is the solution to the problem?

**Comment by materia-project** [comment]
any commits on this solution?

**Comment by vitorgamer58** [comment]
@rahulkhairnarr how did you manage to add a cryptonote based currency ??

**Comment by vitorgamer58** [comment]
Refer to https://github.com/peatio/peatio/issues/650
