### ISSUE TITLE
Mails dont send

### ISSUE THREAD

**Issue by mrkurosawa** [peatio/peatio#661]
If i comment this, email sends. 
```
class BaseMailer < ActionMailer::Base
 # include AMQPQueue::Mailer
```
What for AMQPQueue? And what i need to conf for make it work without commenting?

**Comment by mrkurosawa** [comment]
May be it something with port? I checked
`netstat -tulpn | grep :5672`
`tcp6       0      0 :::5672                 :::*                    LISTEN      12073/beam.smp`
I tryed to change it to 5673 in file amqp.yml, then email sends, with error in console
> `Unable to enqueue :mailer: Could not establish TCP connection to 127.0.0.1:5673: , fallback to synchronous mail delivery`
What's wrong?

**Comment by mrkurosawa** [comment]
Well i googled and find out what beam.smp is rabbitmq daemon and 
`sudo rabbitmqctl list_queues`
returns
`peatio.notification.email       2`
Each new email request increase number. But why?

**Comment by mrkurosawa** [comment]
i changed to production and it's not help only css and js stop loading for some reason

**Comment by rgtoffolo** [comment]
Does your daemons started ?

**Comment by mrkurosawa** [comment]
> Are your daemons started ?
Yep. atleast in admin panel all statuses is running and daemons:start doesnot show any errrors

**Comment by mrkurosawa** [comment]
Can i manually send queue rabbitmqctl? What command do this? because i see 8 messages in email notifications in queue but they dont releasing

**Comment by mrkurosawa** [comment]
After rebooting server it seems what somehow it started to work.
