### ISSUE TITLE
Pusher daemon

### ISSUE THREAD

**Issue by entick** [peatio/peatio#664]
`I, [2017-12-09T16:43:50.822737 #22284]  INFO -- : *** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
E, [2017-12-09T16:43:50.823363 #22284] ERROR -- : stream closed (IOError)

E, [2017-12-09T16:43:50.823467 #22284] ERROR -- : failed to allocate memory (NoMemoryError)

E, [2017-12-09T16:43:50.823505 #22284] ERROR -- : stack level too deep (SystemStackError)

E, [2017-12-09T16:43:50.823633 #22284] ERROR -- : exception reentered (fatal)

E, [2017-12-09T16:43:50.835841 #22284] ERROR -- : Value will be available once the pipeline executes. (Redis::FutureNotReady)

E, [2017-12-09T16:43:50.839611 #22284] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `read_nonblock'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `block in read_fully'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `loop'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `read_fully'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/transport.rb:199:in `read_next_frame'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:63:in `run_once'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:33:in `block in run_loop'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `loop'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `run_loop'
E, [2017-12-09T16:43:50.852610 #22284] ERROR -- : no such frame (ArgumentError)

E, [2017-12-09T16:43:50.852723 #22284] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `read_nonblock'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:41:in `block in read_fully'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `loop'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/cruby/socket.rb:40:in `read_fully'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/transport.rb:199:in `read_next_frame'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:63:in `run_once'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:33:in `block in run_loop'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `loop'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `run_loop'
E, [2017-12-09T16:43:50.857507 #22284] ERROR -- : no such frame (ArgumentError)
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:502:in `load_missing_constant'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:184:in `const_missing'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/rspec-core-2.14.7/lib/rspec/core/backward_compatibility.rb:14:in `const_missing'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/inflector/methods.rb:241:in `const_get'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/inflector/methods.rb:241:in `block in constantize'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/inflector/methods.rb:224:in `each'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/inflector/methods.rb:224:in `inject'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/inflector/methods.rb:224:in `constantize'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:535:in `get'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:566:in `constantize'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/inheritance.rb:121:in `block in compute_type'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/inheritance.rb:119:in `each'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/inheritance.rb:119:in `compute_type'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/reflection.rb:178:in `klass'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/associations/association.rb:123:in `klass'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/associations/belongs_to_association.rb:34:in `find_target?'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/associations/association.rb:147:in `load_target'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/associations/association.rb:54:in `reload'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/associations/singular_association.rb:9:in `reader'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/associations/builder/association.rb:70:in `bid'
/home/entick/workspace/peatio/app/models/trade.rb:49:in `trigger_notify'
/home/entick/workspace/peatio/app/models/worker/pusher_market.rb:6:in `process'
/home/entick/workspace/peatio/lib/daemons/amqp_daemon.rb:61:in `block (2 levels) in <top (required)>'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/channel.rb:1672:in `block in handle_frameset'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `call'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `block (2 levels) in run_loop'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `loop'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `block in run_loop'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `catch'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `run_loop'
E, [2017-12-09T16:43:50.857624 #22284] ERROR -- : uninitialized constant Trade::OrderBid (NameError)
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/inflector/methods.rb:241:in `const_get'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/inflector/methods.rb:241:in `block in constantize'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/inflector/methods.rb:224:in `each'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/inflector/methods.rb:224:in `inject'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/inflector/methods.rb:224:in `constantize'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/inheritance.rb:121:in `block in compute_type'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/inheritance.rb:119:in `each'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/inheritance.rb:119:in `compute_type'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/reflection.rb:178:in `klass'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/associations/association.rb:123:in `klass'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/associations/belongs_to_association.rb:34:in `find_target?'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/associations/association.rb:147:in `load_target'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/associations/association.rb:54:in `reload'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/associations/singular_association.rb:9:in `reader'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/associations/builder/association.rb:70:in `bid'
/home/entick/workspace/peatio/app/models/trade.rb:49:in `trigger_notify'
/home/entick/workspace/peatio/app/models/worker/pusher_market.rb:6:in `process'
/home/entick/workspace/peatio/lib/daemons/amqp_daemon.rb:61:in `block (2 levels) in <top (required)>'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/channel.rb:1672:in `block in handle_frameset'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `call'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `block (2 levels) in run_loop'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `loop'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `block in run_loop'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `catch'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `run_loop'
E, [2017-12-09T16:43:50.857870 #22284] ERROR -- : no such frame (ArgumentError)
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:502:in `load_missing_constant'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:184:in `const_missing'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/rspec-core-2.14.7/lib/rspec/core/backward_compatibility.rb:14:in `const_missing'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/inflector/methods.rb:241:in `const_get'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/inflector/methods.rb:241:in `block in constantize'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/inflector/methods.rb:224:in `each'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/inflector/methods.rb:224:in `inject'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/inflector/methods.rb:224:in `constantize'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:535:in `get'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:566:in `constantize'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/inheritance.rb:121:in `block in compute_type'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/inheritance.rb:119:in `each'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/inheritance.rb:119:in `compute_type'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/reflection.rb:178:in `klass'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/associations/association.rb:123:in `klass'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/associations/belongs_to_association.rb:34:in `find_target?'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/associations/association.rb:147:in `load_target'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/associations/association.rb:54:in `reload'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/associations/singular_association.rb:9:in `reader'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/associations/builder/association.rb:70:in `member'
/home/entick/workspace/peatio/app/models/trade.rb:48:in `trigger_notify'
/home/entick/workspace/peatio/app/models/worker/pusher_market.rb:6:in `process'
/home/entick/workspace/peatio/lib/daemons/amqp_daemon.rb:61:in `block (2 levels) in <top (required)>'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/channel.rb:1672:in `block in handle_frameset'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `call'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `block (2 levels) in run_loop'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `loop'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `block in run_loop'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `catch'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `run_loop'
E, [2017-12-09T16:43:50.857934 #22284] ERROR -- : uninitialized constant Order::Member (NameError)
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/inflector/methods.rb:241:in `const_get'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/inflector/methods.rb:241:in `block in constantize'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/inflector/methods.rb:224:in `each'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/inflector/methods.rb:224:in `inject'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/inflector/methods.rb:224:in `constantize'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/inheritance.rb:121:in `block in compute_type'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/inheritance.rb:119:in `each'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/inheritance.rb:119:in `compute_type'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/reflection.rb:178:in `klass'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/associations/association.rb:123:in `klass'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/associations/belongs_to_association.rb:34:in `find_target?'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/associations/association.rb:147:in `load_target'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/associations/association.rb:54:in `reload'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/associations/singular_association.rb:9:in `reader'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activerecord-4.0.12/lib/active_record/associations/builder/association.rb:70:in `member'
/home/entick/workspace/peatio/app/models/trade.rb:48:in `trigger_notify'
/home/entick/workspace/peatio/app/models/worker/pusher_market.rb:6:in `process'
/home/entick/workspace/peatio/lib/daemons/amqp_daemon.rb:61:in `block (2 levels) in <top (required)>'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/channel.rb:1672:in `block in handle_frameset'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `call'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `block (2 levels) in run_loop'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `loop'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `block in run_loop'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `catch'
/home/entick/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `run_loop'`

**Comment by scatterp** [comment]
check your redis server is running

**Comment by rbgtbusiness** [comment]
It can be low memory to run all daemons and peatio website simultaneously. How much memory do you have on your server ?

**Comment by entick** [comment]
![image](https://user-images.githubusercontent.com/15226168/33834309-37049fcc-de8b-11e7-877a-f54ffcba873d.png)

top left - memory usage
mid left - redis-cli --stat

**Comment by entick** [comment]
This problem is only when i try to replace my pusher app in eu cluster

**Comment by rbgtbusiness** [comment]
Did you already check your Pusher dashboard to check if notifications are reaching there ? You need to check if you pusher application is located on MT1, as well.

**Comment by entick** [comment]
Of course. If I place my application in MT1 - everything works fine. But on another clusters with changes like this - https://github.com/rubykube/peatio/commit/1a23ec09b98bf66f8b371bdd3374e7f335f19172 i see a couple of errors like above

**Comment by rbgtbusiness** [comment]
In this case, you must change your HOST address (api-us.pusher.com). 
     https://pusher.com/docs/clusters

**Comment by entick** [comment]
Works fine. Thank you
