### ISSUE TITLE
How to inform Peatio on new coin deposits 

### ISSUE THREAD

**Issue by rahulkhairnarr** [peatio/peatio#666]
I am working on Bytecoin integration. I had added all api but unable to see the receive coin. How to inform Peatio using webhook via json

**Comment by vetal20600** [comment]
have you tried to implement webhook somehow? show your webhook controller

**Comment by rahulkhairnarr** [comment]
I had inform using webhook but it is giving "ERROR -- : Failed to deposit: undefined method `gsub' for nil:NilClass" this error after webhook

**Comment by vetal20600** [comment]
maybe there is an error in webhook_controller.rb
you have to post it here

**Comment by rahulkhairnarr** [comment]
`class WebhooksController < ApplicationController
	before_action :auth_anybody!
	skip_before_filter :verify_authenticity_token
	def tx
		if params[:type] == "transaction" && params[:hash].present?
			AMQPQueue.enqueue(:deposit_coin, txid: params[:hash], channel_key: "satoshi")
			render :json => { :status => "queued" }
		end
	end
	def eth
		if params[:type] == "transaction" && params[:hash].present?
			AMQPQueue.enqueue(:deposit_coin, txid: params[:hash], channel_key: "ether")
			render :json => { :status => "queued" }
		end
	end
	def icc
		if params[:type] == "transaction" && params[:hash].present?
			AMQPQueue.enqueue(:deposit_coin, txid: params[:hash], channel_key: "incubcoin")
			render :json => { :status => "queued" }
		end
	end
end
`

THis is my web controller

Does Blockchain url is mandetory?

**Comment by tihualong** [comment]
what the hell,  pls paste the complete error stack trace and reformat you code
