### ISSUE TITLE
Blockchain url is mandetory?

### ISSUE THREAD

**Issue by rahulkhairnarr** [peatio/peatio#671]
Hey guys does,  i am getting this error "E, [2017-12-13T19:54:22.682106 #8533] ERROR -- : /home/rahul/peatio/app/models/currency.rb:59:in `blockchain_url'
/home/rahul/peatio/app/models/concerns/deposits/coinable.rb:32:in `blockchain_url'
/home/rahul/peatio/app/models/concerns/deposits/coinable.rb:39:in `as_json'
/home/rahul/peatio/app/models/deposit.rb:138:in `sync_create'
"

Is blockchain url is mandetory

**Comment by amarian12** [comment]
for code to work yes, but can be:

  blockchain: https://nonexistingdomain/tx/#{txid}
  address_url: https://nonexistingdomain/address/#{address}

**Comment by rahulkhairnarr** [comment]
Thanks it works
