### ISSUE TITLE
Fiat money deposit/withdrawl dont work. 

### ISSUE THREAD

**Issue by senisende** [peatio/peatio#678]
Hi,

I tried to add eur money to my account, but it doesnt work. ı need help!

**Comment by senisende** [comment]
i solved.

**Comment by gsilvestri** [comment]
Please indicate how to solve the issue in the closing comment.

**Comment by scatterp** [comment]
see my commit history i its in scatterp or scatterp2 scatterp3 or scatterp4 check all of them /peatio

**Comment by gsilvestri** [comment]
the project peatio has no new commit since 3 years ago: can you indicate more clearly what commits you are referring to??

**Comment by senisende** [comment]
Check scatterp fork.

**Comment by scatterp** [comment]
gsilverstiri add me on skype simon.m.day
