### ISSUE TITLE
Is it nessessary to reload all daemons and server after any code change?

### ISSUE THREAD

**Issue by mrkurosawa** [peatio/peatio#692]
I tryed to fix problem when all quick withdrawals(manual proceeds works correctly) stuck in 'processing' status. Fixed it by changing _process if quick?_ to _process! if quick?_ in file withdraw.rb(method audit), but it start work only when i restart all daemons and server. Why?

**Comment by rbgtbusiness** [comment]
The process that you changed is controlled by a daemon. It is not all changes that will require restarting daemons.

**Comment by mrkurosawa** [comment]
> The process that you changed is controlled by a daemon
How can i find out when i need to restart all daemons and when don't? I don't understand how Ruby works so asking so noob questions, but there is no documentation of peatio as far as i know

**Comment by rbgtbusiness** [comment]
You can access the Patio admin panel. There you will find all daemons and their names. It is a good start to understand what they are doing and which processes are controlled by them.

**Comment by mrkurosawa** [comment]
May be, but withdraw.rb is ActiveRecord model. How it linked with daemons i dont know. Well, may be after some time i will understand it better.
