### ISSUE TITLE
No such file or directory @ rb_sysopen - app/views/private/funds/index.json.jbuilder

### ISSUE THREAD

**Issue by mrkurosawa** [peatio/peatio#696]
When i start server with command
`bundle exec rails server`
everything is good, but when i start as a daemon
`bundle exec rails server -d`
That error shows on funds page. Production/development does not matter.

**Comment by mrkurosawa** [comment]
When i create index.json.jbuilder in /app/views/private/funds/ of server it's works, lol. But my peatio root is '/root/peatio'.  How can i fix it? Where to change root folder?

**Comment by scatterp** [comment]
reinstall you should not run peatio as root and servers are started with 
bundle exec rake daemons:start

**Comment by mrkurosawa** [comment]
Yep, reinstalled by production guide and it's start working
