### ISSUE TITLE
Not working on Ubuntu 16 with Ruby 2.2.1 or 2.2.2

### ISSUE THREAD

**Issue by atlanticstarr1** [peatio/peatio#708]
Keep getting this WARNING: ruby-2.2.2 is nearing its end of life.

**Comment by mod** [comment]
on github.com/rubykube/peatio
we upgraded to ruby-2.5.0

**Comment by oskanddr** [comment]
Hello @atlanticstarr1,

I can help you get Peatio running on your private cloud. I also offer development services.

You can always reach me at nimpo1074@gmail.com

Best,
Oskar

**Comment by scatterp** [comment]
@atlanticstarr1 the warning you are seeing is just a warning it can be safely ignored its likely you have some other error you can contact me on skype if you need more help simon.m.day

**Comment by muhammednagy** [comment]
you can ignore that warning 
i'm working on doing an upgrade

**Comment by atlanticstarr1** [comment]
Thanks guys. 
@mod tnx for introducing me to your repo, i haven't tried it as yet but i will.
@scatterp your script worked flawlessly with the only exception being the images/css was messed up. I fixed it though.
@muhammednagy tnx for working on an upgrade. Will give it a go once it's done.

**Comment by peatioMan** [comment]
I can help you with all peatio issues.

Add me on skype, just search Peatio Man or add by id:
cid-(-8618737192104534817)@outlook.com

**Comment by atlanticstarr1** [comment]
tnx for all the responses. closing this issue.
