### ISSUE TITLE
Adding new currency DASH.

### ISSUE THREAD

**Issue by hostsleek** [peatio/peatio#722]
Hi,

I am looking at adding a new currency into PETIO like dash and others.  I have followed the guide under 
https://github.com/peatio/peatio/blob/master/doc/currency.md

-------------
  deposits_dash POST /deposits/dash.rb private/deposits/dash#create
  new_deposits_dash GET /deposits/dash.rb private/deposits/dash#new
-------------

I keep getting error when i try to pre-compile peatio. 

SyntaxError: /home/deploy/peatio/current/config/routes.rb:129: unknown regexp options - dah
/home/deploy/peatio/current/config/routes.rb:130: unknown regexp options - dah

**Comment by hostsleek** [comment]
Sorted..

**Comment by minersbad** [comment]
https://peatio.io/

**Comment by coinlisting** [comment]
which is your error in dash? which daemon used?
