### ISSUE TITLE
redirect localhost:3000

### ISSUE THREAD

**Issue by vitorgamer58** [peatio/peatio#733]
very often while I'm on localhost when clicking on some button peatio does a redirect to localhost:3000/something

when that happens on port 3000 a lot does not load showing only text

something I have to change in the settings ??

**Comment by vitorgamer58** [comment]
![alt](http://i68.tinypic.com/t6z9tg.jpg)

**Comment by KvApril** [comment]
Have you change the URL_HOST with your domain in your config/application.yml?

**Comment by vitorgamer58** [comment]
has been running when I moved to my domain, bolsotrade.tk
but i get this erro on webconsole

`Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":1006,"message":"Connection interrupted (0)"}}}`

**Comment by KvApril** [comment]
I have not see this error.
I guess if there is something connect with your pusher config 
In config/application.yml
```
  PUSHER_APP: YOUR_PUSHER_APP
  PUSHER_KEY: YOUR_PUSHER_KEY
  PUSHER_SECRET: YOUR_PUSHER_SECRET
  PUSHER_HOST: api.pusherapp.com
  PUSHER_PORT: 80
  PUSHER_WS_PORT: 80
  PUSHER_WSS_PORT: 443
  PUSHER_ENCRYPTED: true
```

**Comment by vitorgamer58** [comment]
Yes, i did it
![alt](http://ap.imagensbrasil.org/images/2018/04/09/Screenshot_679.png)

**Comment by vitorgamer58** [comment]
Yes, i did it
![alt](http://ap.imagensbrasil.org/images/2018/04/09/Screenshot_679.png)

**Comment by vitorgamer58** [comment]
i get this 
![alt](https://raw.githubusercontent.com/vitorgamer58/vitorgamer58-images/master/Screenshot_78.png)

**Comment by vitorgamer58** [comment]
i execute `chmod 777 graviex-exchange`
and now i get this 
![alt](https://raw.githubusercontent.com/vitorgamer58/vitorgamer58-images/master/Screenshot_80.png)

**Comment by vitorgamer58** [comment]
Solved
