### ISSUE TITLE
We offer installation with all coins

### ISSUE THREAD

**Issue by coinlisting** [peatio/peatio#756]
we offer installation service with any coin you want.
![schermata 2018-05-29 alle 08 53 49](https://user-images.githubusercontent.com/39408509/40645343-658a80e4-6326-11e8-8f27-93fc2fe399cc.png)
![schermata 2018-05-28 alle 19 31 10](https://user-images.githubusercontent.com/39408509/40645352-6c02f618-6326-11e8-80d0-490daec7c888.png)
https://peatio.io

**Comment by ZahroKa** [comment]
coinlisting , mxo2, salvo, touristcoin and listex are same team of frauders. Be careful people! If you don't want to lose your money, dont use this service. It is a group of unprofessional morons, who do not have any respect for their customers and their opinions.

**Comment by ZahroKa** [comment]
When are you gonna send back our money??

**Comment by coinlisting** [comment]
you are not credible

![schermata 2018-05-31 alle 17 06 46](https://user-images.githubusercontent.com/39408509/40790409-26bdc878-64f5-11e8-84af-ecfe6928c8e1.png)

**Comment by ZahroKa** [comment]
![billede](https://user-images.githubusercontent.com/39796219/40790588-a3e94ed0-64f5-11e8-9b3f-b08b9f37ebf6.png)
I am here because of you. We don't want your service. We didn't get anything from you . Return our money. You have spent 2 days of our time.

**Comment by coinlisting** [comment]
the name of this man is Madina Karieva  and from Denmark
Him dont answer to developer for delivery work. Is him problem
![schermata 2018-05-31 alle 17 15 33](https://user-images.githubusercontent.com/39408509/40790837-4bc3accc-64f6-11e8-878e-d89acce5c17e.png)
bye now and dont lose to us other time

**Comment by ZahroKa** [comment]
![billede](https://user-images.githubusercontent.com/39796219/40791020-b807e0ce-64f6-11e8-9b3c-d07b65785770.png)
Here is an example of how they talk

**Comment by coinlisting** [comment]
you can not register with fake names a few minutes ago and make comments. You are also stupid without really saying your name. Here are our emails and you did not want the job. Therefore do not waste people time. Stupid

**Comment by coinlisting** [comment]
![schermata 2018-05-31 alle 17 20 23](https://user-images.githubusercontent.com/39408509/40791092-e9e28504-64f6-11e8-8283-81f7d72a1072.png)
confirm that is the stupid of denmark
bye good luck
