### ISSUE TITLE
Bundle Install Issue

### ISSUE THREAD

**Issue by ElectroCreator** [peatio/peatio#761]
Hi, im having issues with bundle install.

I did all the steps correctly, im running on ubuntu 14 64 bit.

when im in the peatio directory

`cd peatio`
and then i run bundle install
`bundle install`

I get the following issues:
![untitled](https://user-images.githubusercontent.com/26846481/40879697-a305cb56-6658-11e8-85b2-d1faec1e3731.png)

I hope you guys can help me with this. Help is appreciated

**Comment by pkdcryptos** [comment]
Which repo link/install script you are using ?  

Anyway please pick those gems from https://github.com/muhammednagy/

**Comment by coinlisting** [comment]
contact me give me your skype

**Comment by ElectroCreator** [comment]
@pkdcryptos what do you mean?

@coinlisting you can help me fix the issues?

**Comment by coinlisting** [comment]
Yes we can help U
