### ISSUE TITLE
How do I edit the frontpage?

### ISSUE THREAD

**Issue by ElectroCreator** [peatio/peatio#762]
Hi.

I deployed Peatio, and im trying to edit the front page. (Starting Page)

I looked for the file but could not find it.
could someone please help me?

**Comment by coinlisting** [comment]
we have do all 
https://listex.io

**Comment by ElectroCreator** [comment]
@coinlisting  I already got it working.

**Comment by ndacoin** [comment]
@ElectroCreator Please let me know how I can frontpage, Logo, favicon etc
