### ISSUE TITLE
Peatio customization, deployment looking for developers

### ISSUE THREAD

**Issue by cryptokq** [peatio/peatio#785]
Hi i'm looking to put together a team to ship peatio to production

Looking for backend, front end, devops devs who know their shit.
ICO devs, digital marketers, fintech/banking experts also welcome.

Get in touch
Skype @cryptokq
Email cryptokq@outlook.com
Telegram https://t.me/joinchat/HdEl4Ehjx9RMEh6mgxWh0A

**Comment by samsoft00** [comment]
Hey @cryptokq 
Are you looking for Peatio Developer or someone to customize Peatio frontend for you? search no more, click on the link http://www.fiverr.com/s2/4a93682859, click on sign up (register), and search Peatio, drop a message and will get back to you.
Regards

**Comment by algobasket** [comment]
Our Peatio 
https://bongo.network
Contact Us
Skype : algobasket
Email : algobasket@gmail.com
Phone : +918800580884

**Comment by algobasket** [comment]
@cryptokq 
'm a freelancer peatio developer   , 
i installed everything in peatio for production .  
https://bongo.network/

**Comment by samsoft00** [comment]
that's great new, but you install version 0.2.1 instead of the current version (Currently v1.9.0.alpha), why?

**Comment by Apollo-IT** [comment]
https://github.com/Apollo-IT

**Comment by mishul** [comment]
@cryptokq 
We deploy industry level Peatio. Have an entire team working with it - can add any infrastructure modifications, wallet integrations and scalable solutions. We provide a good amount of coins to start with.

Please reach out on skype/email: mgupta14@illinois.edu

Looking forward to hear from you!

**Comment by AntechIndia** [comment]
Tap on the huge potential of Peatio script and build your own exchange conveniently. It is an open-source, secure, scalable and free software. Our **[Peatio developers](Website :https://antiersolutions.com/cryptocurrency-exchange-development-company.html)** are fully versed in implementing the ideal strategies and functionalities to set up your exchange right.
For more details reach us :
Skype : exchange@antiersolutions.com
Email: info@antiersolutions.com

**Comment by algobasket** [comment]
Our Peatio
http://bongo.network
Contact Us
Skype : algobasket
Email : algobasket@gmail.com
Phone : +918800580884

**Comment by caherrerapa** [comment]
@cryptokq Telegram +1 724 467 1422

**Comment by therealredvoid** [comment]
@algobasket is SCAMMER
