### ISSUE TITLE
Error ! Please

### ISSUE THREAD

**Issue by algobasket** [peatio/peatio#805]
Visit http://peatio.algobasket.com/
Skype : algobasket

**Comment by sha422** [comment]
Vulnerable, beware people!

**Comment by MatheusGrijo** [comment]
Scammer!!!!!!!!!!!!!!!!!!!!!!!!!!
He stole me 0.5 BTC!!!!
I have the conversation screens!

**Comment by dudetheman** [comment]
algobasket stole my money too. POS! I have proof as well!

**Comment by dudetheman** [comment]
Not scammer. I can prove from skype conversatios. THIEF! you stopped communications after I paid you!

**Comment by RubyKubeDev** [comment]
coinlisting , mxo2, salvo, touristcoin, listex,dudetheman and thedabest are same team of frauders. 
Be careful people! If you don't want to lose your money, dont use this service. It is a group of 
unprofessional morons, who do not have any respect for their customers and their opinions.
Scam 1 = #823
Scam 2 = #819
Scam 3 = #747
The same scammer guy making multiple accounts ! Alert !
