### ISSUE TITLE
run server in background

### ISSUE THREAD

**Issue by aminaqi** [peatio/peatio#814]
i want to run server in background, don't want to use bundle exec rails server
i've installed passenger using this
https://github.com/peatio/peatio/blob/master/doc/deploy-production-server.md
i want to use my VPS ip to put in browser and it shows the exchange

**Comment by algobasket** [comment]
@aminaqi in localhost only you need to run AppServer (bundle exec rails server) , for the live server you only need to use Nginx + Passenger .If you want to use your VPS external (public IP) to view the exchange in the browser then set the Bridge in networking option Or simple use Vagrant for simplicity.
