### ISSUE TITLE
ArgumentError: 'private/deposits/zecßes' is not a supported controller name

### ISSUE THREAD

**Issue by Thananjaya** [peatio/peatio#844]
I ma getting an error `ArgumentError: 'private/deposits/zecßes' is not a supported controller name`, but there is no such controller under `private/deposits` folder. The error message is 

`ArgumentError: 'private/deposits/zecßes' is not a supported controller name. This can lead to potential routing problems. See http://guides.rubyonrails.org/routing.html#specifying-a-controller-to-use`

There is a controller named `zecs`, but not the one mentioned in the error log! Did anyone came across this error. Thanks in advance if anyone would help to resolve this issue.

**Comment by scatterp** [comment]
Let's start with some environmental variables, configuration and background to how you got to that.

**Comment by Thananjaya** [comment]
@scatterp, I have resolved this issue. thanks for the response!
